//
// Generated by JTB 1.3.2
//

package visitor;
import syntaxtree.*;
import java.util.*;

/**
 * Provides default methods which visit each node in the tree in depth-first
 * order.  Your visitors may extend this class.
 */
public class DepthFirstVisitor implements Visitor {
   public LinearScanAlgoApp lsa= new LinearScanAlgoApp();
   boolean incallarg = false;
   boolean instartinglabel = false;
   int globalfunintlit = 0;
   boolean infunclit = false;
   boolean intemplit = true;
   int counter =0;
   public DepthFirstVisitor(){};
   // public DepthFirstVisitor(Vector<Pair<Integer,Integer>> v1){
   //    lsa.intervalinfo = v1 ;
   // }
   String tempnostring = new String();
   String currfunlabel = new String();
   //
   // Auto class visitors--probably don't need to be overridden.
   //
   public void visit(NodeList n) {
      for ( Enumeration<Node> e = n.elements(); e.hasMoreElements(); )
         e.nextElement().accept(this);
   }

   public void visit(NodeListOptional n) {
      if ( n.present() )
         for ( Enumeration<Node> e = n.elements(); e.hasMoreElements(); )
            e.nextElement().accept(this);
   }

   public void visit(NodeOptional n) {
      if ( n.present() )
         n.node.accept(this);
   }

   public void visit(NodeSequence n) {
      for ( Enumeration<Node> e = n.elements(); e.hasMoreElements(); )
         e.nextElement().accept(this);
   }

   public void visit(NodeToken n) { }

   //
   // User-generated visitor methods below
   //

   /**
    * f0 -> "MAIN"
    * f1 -> StmtList()
    * f2 -> "END"
    * f3 -> ( Procedure() )*
    * f4 -> <EOF>
    */
   public void visit(Goal n) {
      currfunlabel = "MAIN";
      lsa.funcallsinfo.put(currfunlabel,0);
      lsa.fun_maxtemp.put(currfunlabel,0);
      lsa.fun_argcnt.put(currfunlabel,0);
      lsa.is_caller.put(currfunlabel,false);
      n.f0.accept(this);
      n.f1.accept(this);
      n.f2.accept(this);
      currfunlabel = "";
      n.f3.accept(this);
      n.f4.accept(this);
   }

   /**
    * f0 -> ( ( Label() )? Stmt() )*
    */
   public void visit(StmtList n) {
      n.f0.accept(this);
   }

   /**
    * f0 -> Label()
    * f1 -> "["
    * f2 -> IntegerLiteral()
    * f3 -> "]"
    * f4 -> StmtExp()
    */
   public void visit(Procedure n) {
      instartinglabel = true;
      n.f0.accept(this);
      instartinglabel = false;
      n.f1.accept(this);
      lsa.funcallsinfo.put(currfunlabel,0);
      lsa.fun_maxtemp.put(currfunlabel,0);
      lsa.is_caller.put(currfunlabel,false);
      infunclit = true;
      n.f2.accept(this);
      infunclit = false;
      // System.out.println(globalfunintlit);
      lsa.fun_argcnt.put(currfunlabel,globalfunintlit);
      n.f3.accept(this);
      n.f4.accept(this);
      currfunlabel = "";
      globalfunintlit =0;
   }

   /**
    * f0 -> NoOpStmt()
    *       | ErrorStmt()
    *       | CJumpStmt()
    *       | JumpStmt()
    *       | HStoreStmt()
    *       | HLoadStmt()
    *       | MoveStmt()
    *       | PrintStmt()
    */
   public void visit(Stmt n) {
      n.f0.accept(this);
   }

   /**
    * f0 -> "NOOP"
    */
   public void visit(NoOpStmt n) {
      n.f0.accept(this);
   }

   /**
    * f0 -> "ERROR"
    */
   public void visit(ErrorStmt n) {
      n.f0.accept(this);
   }

   /**
    * f0 -> "CJUMP"
    * f1 -> Temp()
    * f2 -> Label()
    */
   public void visit(CJumpStmt n) {
      n.f0.accept(this);
      n.f1.accept(this);
      n.f2.accept(this);
   }

   /**
    * f0 -> "JUMP"
    * f1 -> Label()
    */
   public void visit(JumpStmt n) {
      n.f0.accept(this);
      n.f1.accept(this);
   }

   /**
    * f0 -> "HSTORE"
    * f1 -> Temp()
    * f2 -> IntegerLiteral()
    * f3 -> Temp()
    */
   public void visit(HStoreStmt n) {
      n.f0.accept(this);
      n.f1.accept(this);
      n.f2.accept(this);
      n.f3.accept(this);
   }

   /**
    * f0 -> "HLOAD"
    * f1 -> Temp()
    * f2 -> Temp()
    * f3 -> IntegerLiteral()
    */
   public void visit(HLoadStmt n) {
      n.f0.accept(this);
      n.f1.accept(this);
      n.f2.accept(this);
      n.f3.accept(this);
   }

   /**
    * f0 -> "MOVE"
    * f1 -> Temp()
    * f2 -> Exp()
    */
   public void visit(MoveStmt n) {
      n.f0.accept(this);
      n.f1.accept(this);
      n.f2.accept(this);
   }

   /**
    * f0 -> "PRINT"
    * f1 -> SimpleExp()
    */
   public void visit(PrintStmt n) {
      n.f0.accept(this);
      n.f1.accept(this);
   }

   /**
    * f0 -> Call()
    *       | HAllocate()
    *       | BinOp()
    *       | SimpleExp()
    */
   public void visit(Exp n) {
      n.f0.accept(this);
   }

   /**
    * f0 -> "BEGIN"
    * f1 -> StmtList()
    * f2 -> "RETURN"
    * f3 -> SimpleExp()
    * f4 -> "END"
    */
   public void visit(StmtExp n) {
      n.f0.accept(this);
      n.f1.accept(this);
      n.f2.accept(this);
      n.f3.accept(this);
      n.f4.accept(this);
   }

   /**
    * f0 -> "CALL"
    * f1 -> SimpleExp()
    * f2 -> "("
    * f3 -> ( Temp() )*
    * f4 -> ")"
    */
   public void visit(Call n) {
      lsa.is_caller.put(currfunlabel,true);
      n.f0.accept(this);
      n.f1.accept(this);
      n.f2.accept(this);
      incallarg = true;
      n.f3.accept(this);
      n.f4.accept(this);
      // if(lsa.funcallsinfo.containsKey(currfunlabel)){
         int presentcount = lsa.funcallsinfo.get(currfunlabel);
         presentcount = Integer.max(presentcount,counter);
         lsa.funcallsinfo.put(currfunlabel,presentcount);
      // }else{
      //    lsa.funcallsinfo.put(currfunlabel,counter);
      // }
      incallarg = false;
      counter =0;
   }

   /**
    * f0 -> "HALLOCATE"
    * f1 -> SimpleExp()
    */
   public void visit(HAllocate n) {
      n.f0.accept(this);
      n.f1.accept(this);
   }

   /**
    * f0 -> Operator()
    * f1 -> Temp()
    * f2 -> SimpleExp()
    */
   public void visit(BinOp n) {
      n.f0.accept(this);
      n.f1.accept(this);
      n.f2.accept(this);
   }

   /**
    * f0 -> "LE"
    *       | "NE"
    *       | "PLUS"
    *       | "MINUS"
    *       | "TIMES"
    *       | "DIV"
    */
   public void visit(Operator n) {
      n.f0.accept(this);
   }

   /**
    * f0 -> Temp()
    *       | IntegerLiteral()
    *       | Label()
    */
   public void visit(SimpleExp n) {
      n.f0.accept(this);
   }

   /**
    * f0 -> "TEMP"
    * f1 -> IntegerLiteral()
    */
   public void visit(Temp n) {
      if(incallarg){
         counter++;
      }
      n.f0.accept(this);
      intemplit = true;
      n.f1.accept(this);
      intemplit = false;
      int tempno = Integer.valueOf(tempnostring);
      int maxtemp = lsa.fun_maxtemp.get(currfunlabel);
      maxtemp = Integer.max(maxtemp,tempno);
      lsa.fun_maxtemp.put(currfunlabel,maxtemp);
   }

   /**
    * f0 -> <INTEGER_LITERAL>
    */
   public void visit(IntegerLiteral n) {
      if(intemplit){
      tempnostring = n.f0.toString();
      }
      if(infunclit){
         globalfunintlit = Integer.valueOf(n.f0.toString());
      }
   }

   /**
    * f0 -> <IDENTIFIER>
    */
   public void visit(Label n) {
      if(instartinglabel){
      currfunlabel = n.f0.toString();
      }
   }

}
