//
// Generated by JTB 1.3.2
//

package visitor;
import syntaxtree.*;
import java.util.*;

/**
 * Provides default methods which visit each node in the tree in depth-first
 * order.  Your visitors may extend this class.
 */
public class GJNoArguDepthFirst<R> implements GJNoArguVisitor<R> {
   public LinearScanAlgoApp finalinfo = new LinearScanAlgoApp();
   public GJNoArguDepthFirst(LinearScanAlgoApp finalinfo1){
          finalinfo = finalinfo1;
   }
   String currfunlabel = new String();
   String prerequisites = new String();
   String lastprerequisite = new String();
   boolean incallfunc = false; //exception for call function prerequsite order
   boolean incallargtemps = false;
   int argcounter = 0;
   boolean inmovefirst = false;
   boolean isspilled = false;
   boolean v1 = false;
   int movefirstcorrespondence = 0;
   String  returncalltemp = new String();
   boolean isexpcall = false;
   //
   // Auto class visitors--probably don't need to be overridden.
   //
   public R visit(NodeList n) {
      R _ret=null;
      int _count=0;
      for ( Enumeration<Node> e = n.elements(); e.hasMoreElements(); ) {
         e.nextElement().accept(this);
         _count++;
      }
      return _ret;
   }

   public R visit(NodeListOptional n) {
      if ( n.present() ) {
         R _ret=null;
         int _count=0;
         for ( Enumeration<Node> e = n.elements(); e.hasMoreElements(); ) {
            e.nextElement().accept(this);
            _count++;
         }
         return _ret;
      }
      else
         return null;
   }

   public R visit(NodeOptional n) {
      if ( n.present() )
         return n.node.accept(this);
      else
         return null;
   }

   public R visit(NodeSequence n) {
      R _ret=null;
      int _count=0;
      for ( Enumeration<Node> e = n.elements(); e.hasMoreElements(); ) {
         e.nextElement().accept(this);
         _count++;
      }
      return _ret;
   }

   public R visit(NodeToken n) { return null; }

   //
   // User-generated visitor methods below
   //

   /**
    * f0 -> "MAIN"
    * f1 -> StmtList()
    * f2 -> "END"
    * f3 -> ( Procedure() )*
    * f4 -> <EOF>
    */
   public R visit(Goal n) {
      R _ret=null;
      currfunlabel = "MAIN";
      n.f0.accept(this);
      R stmtlist = n.f1.accept(this);
      // System.out.println("\na\n"+  stmtlist.toString() + "\nb\n");
      String checkspilled = "NOT SPILLED";
      if(!(finalinfo.tempinfo.get("MAIN").spilledreginfo.isEmpty())){
         checkspilled = "SPILLED";
      }
      n.f2.accept(this);
      String intlit2 = Integer.toString(finalinfo.tempinfo.get(currfunlabel).stackcount);
      String intlit3 = Integer.toString(finalinfo.funcallsinfo.get(currfunlabel));
      currfunlabel = "";
      String procedurelist = new String();
      for ( Enumeration<Node> e = n.f3.elements(); e.hasMoreElements(); ) {
         procedurelist+= (e.nextElement().accept(this).toString() );
      }
      n.f4.accept(this);
      System.out.println("MAIN   [ 0 ] [ " + intlit2 + " ]  [ " + intlit3 + " ] \n" + stmtlist.toString() + "\nEND\n" + "// " + checkspilled + "\n" +  procedurelist );
      return _ret;
   }

   /**
    * f0 -> ( ( Label() )? Stmt() )*
    */
   public R visit(StmtList n) {
      // System.out.println("stmtlist start:");
      R _ret=null;
      // n.f0.accept(this);
       String temp = new String();
      for ( Enumeration<Node> e = n.f0.elements(); e.hasMoreElements(); ) {
         NodeSequence seq = (NodeSequence)e.nextElement();
         for(Enumeration<Node> f = seq.elements(); f.hasMoreElements();){
            Node current = f.nextElement();
            if(current instanceof NodeOptional){
              NodeOptional nodeopt = (NodeOptional)current;
              if(nodeopt.present()){
               temp += (String)(nodeopt.node.accept(this)) + "  ";
              }
         }else{
            String stmtsinfo = (String)(current.accept(this));
            if(!prerequisites.equals("")){
                temp+= prerequisites + "\n";
               //  System.out.println("\nyyyyy\n"+prerequisites+ "\nyyyyy\n");
                prerequisites = "";
            }
            // System.out.println(prerequisites );
            // System.out.println(stmtsinfo + "jk");
            temp += stmtsinfo  + "\n";
            // System.out.println("\nxxxx\n"+ stmtsinfo + "\nxxxx\n");
            // System.out.println("\nxxxx\n" + temp + "\nxxxxx\n");
         }
         }
      }
      // System.out.println("stmtlistend");
      // System.out.println("\na\n"+temp.toString()+ "\nb\n");
      _ret = (R)temp;
      return _ret;
   }

   /**
    * f0 -> Label()
    * f1 -> "["
    * f2 -> IntegerLiteral()
    * f3 -> "]"
    * f4 -> StmtExp()
    */
   public R visit(Procedure n) {
      R _ret=null;
      currfunlabel = n.f0.accept(this).toString();
      n.f1.accept(this);
      String intlit1 = n.f2.accept(this).toString();
      n.f3.accept(this);
      R stmtexpr = n.f4.accept(this);
      String reloading = new String();
      int reqargs = Integer.min(4,Integer.valueOf(intlit1));
      for(int i=0;i<reqargs;i++){
         String correspondence = new String();
         RegAllocMap r = finalinfo.regallocinfo.get(currfunlabel);
         if(r.spilledvars.contains(i)){
            FuncStackinfo f = finalinfo.tempinfo.get(currfunlabel);
            if(!(f.spilledreginfo.containsKey(i))){
               int presentstckcnt = f.stackcount;
               finalinfo.tempinfo.get(currfunlabel).spilledreginfo.put(i,presentstckcnt);
               finalinfo.tempinfo.get(currfunlabel).stackcount++;
            }
            reloading+=("ASTORE SPILLEDARG " + Integer.toString(f.spilledreginfo.get(i)) + " a" + i + "\n");
         }else{
            if(r.smapping.containsKey(i)){
               correspondence = "s"+ Integer.toString(r.smapping.get(i));
            }else{
               correspondence = "t"+ Integer.toString(r.tmapping.get(i));
            }
            reloading+=("MOVE " + correspondence + " a" + i + "\n" );
         }

      }
      // for(int i=4;i<Integer.valueOf(intlit1);i++){
      //    String correspondence = new String();
      //    RegAllocMap r = finalinfo.regallocinfo.get(currfunlabel);
      //    if(r.spilledvars.contains(i)){
      //       FuncStackinfo f = finalinfo.tempinfo.get(currfunlabel);
      //       if(!(f.spilledreginfo.containsKey(i))){
      //          int presentstckcnt = f.stackcount;
      //          finalinfo.tempinfo.get(currfunlabel).spilledreginfo.put(i,presentstckcnt);
      //          finalinfo.tempinfo.get(currfunlabel).stackcount++;
      //       }
      //       reloading+=("ALOAD  v0 SPILLEDARG " + Integer.toString(i-4)+ "\n");
      //       reloading+=("ASTORE  SPILLEDARG  " + Integer.toString(f.spilledreginfo.get(i))+ " v0 \n");

      //    }else{
      //       if(r.smapping.containsKey(i)){
      //          correspondence = "s"+ Integer.toString(r.smapping.get(i));
      //       }else{
      //          correspondence = "t"+ Integer.toString(r.tmapping.get(i));
      //       }
      //       reloading+=("ALOAD " + correspondence + "SPILLEDARG " + Integer.toString(i-4) + "\n ");
      //    }
      // }
      String checkspilled = "NOT SPILLED";
      if(!(finalinfo.tempinfo.get(currfunlabel).spilledreginfo.isEmpty())){
         checkspilled = "SPILLED";
      }
      String intlit2 = Integer.toString(finalinfo.tempinfo.get(currfunlabel).stackcount);
      String intlit3 = Integer.toString(finalinfo.funcallsinfo.get(currfunlabel));
      String calleesavedinfo = new String();
      FuncStackinfo f = finalinfo.tempinfo.get(currfunlabel);
      for(int i=0;i<8;i++){
         calleesavedinfo += ("ASTORE  SPILLEDARG  " + Integer.toString(f.smappings.get(i)) + " s" + i + "\n "  );
      }
      String loadcallees = new String();
      for(int i=0;i<8;i++){
         loadcallees += ("ALOAD  s" + i + " SPILLEDARG  " + Integer.toString(f.smappings.get(i)) + "\n "  );
      }

      _ret = (R)(currfunlabel + "  [ " + intlit1 + " ]   [ " + intlit2 + " ]   [ " + intlit3 + " ] \n" +
                calleesavedinfo + 
                reloading + 
                stmtexpr.toString() + "\n" +
                loadcallees + "\n"+
                "\nEND\n//  " + checkspilled + "\n");
      currfunlabel = "";

      return _ret;
   }

   /**
    * f0 -> NoOpStmt()
    *       | ErrorStmt()
    *       | CJumpStmt()
    *       | JumpStmt()
    *       | HStoreStmt()
    *       | HLoadStmt()
    *       | MoveStmt()
    *       | PrintStmt()
    */
   public R visit(Stmt n) {
      R _ret=null;
      return n.f0.accept(this);
   }

   /**
    * f0 -> "NOOP"
    */
   public R visit(NoOpStmt n) {
      R _ret=null;
      n.f0.accept(this);
      _ret = (R)("NOOP");
      return _ret;
   }

   /**
    * f0 -> "ERROR"
    */
   public R visit(ErrorStmt n) {
      R _ret=null;
      n.f0.accept(this);
      _ret = (R)("ERROR");
      return _ret;
   }

   /**
    * f0 -> "CJUMP"
    * f1 -> Temp()
    * f2 -> Label()
    */
   public R visit(CJumpStmt n) {
      R _ret=null;
      n.f0.accept(this);
      R temp1 = n.f1.accept(this);
      R labelstring = n.f2.accept(this);
      _ret = (R)("CJUMP  " + temp1.toString() + "  " + labelstring.toString() + "\n" );
      return _ret;
   }

   /**
    * f0 -> "JUMP"
    * f1 -> Label()
    */
   public R visit(JumpStmt n) {
      R _ret=null;
      n.f0.accept(this);
      R labelstring = n.f1.accept(this);
      _ret = (R)("JUMP  " + labelstring.toString() + "\n");
      return _ret;
   }

   /**
    * f0 -> "HSTORE"
    * f1 -> Temp()
    * f2 -> IntegerLiteral()
    * f3 -> Temp()
    */
   public R visit(HStoreStmt n) {
      R _ret=null;
      n.f0.accept(this);
      String tempstring1 = n.f1.accept(this).toString();
      String intlit = n.f2.accept(this).toString();
      v1 = true;
      // inmovefirst = true;
      String tempstring2 = n.f3.accept(this).toString();
      // inmovefirst = false;
      v1 = false;
      String hstorestmt = "HSTORE " + tempstring1 + "  " + intlit + " " + tempstring2 + "\n";
      // if(isspilled){
      //    hstorestmt+=("ASTORE  SPILLEDARG " + movefirstcorrespondence + " v1\n");
      //    isspilled = false;
      // }
      _ret = (R)(hstorestmt);
      return _ret;
   }

   /**
    * f0 -> "HLOAD"
    * f1 -> Temp()
    * f2 -> Temp()
    * f3 -> IntegerLiteral()
    */
   public R visit(HLoadStmt n) {
      R _ret=null;
      n.f0.accept(this);
      inmovefirst = true;
      String tempstring1 = n.f1.accept(this).toString();
      inmovefirst = false;
      v1 = true;
      String tempstring2 = n.f2.accept(this).toString();
      v1 = false;
      String intlit = n.f3.accept(this).toString();
      String hloadstmt = "HLOAD " + tempstring1 + "  " + tempstring2 + " " + intlit + "\n";
      if(isspilled){
      hloadstmt+=("ASTORE  SPILLEDARG " + movefirstcorrespondence + " v0\n");
      isspilled = false;

      }
      _ret = (R)(hloadstmt);
      return _ret;
   }

   /**
    * f0 -> "MOVE"
    * f1 -> Temp()
    * f2 -> Exp()
    */
   public R visit(MoveStmt n) {
      // System.out.println("move stmt start");
      R _ret=null;
      n.f0.accept(this);
      inmovefirst = true;
      v1 = true;
      String tempstring = n.f1.accept(this).toString();
      v1 = false;
      inmovefirst = false;
      returncalltemp = tempstring;
      String expr1 = n.f2.accept(this).toString();
      // System.out.println("\n" + expr1.toString()+ "\n");
      String moveexp = new String();
      if(!isexpcall){
      moveexp = "MOVE " + tempstring + "  " + expr1 + "\n";
      }else{
         moveexp = expr1 + "\n";
      }
      if(isspilled){
      moveexp+=("ASTORE  SPILLEDARG " + movefirstcorrespondence + " v1\n");
      isspilled = false;
      }
      _ret = (R)(moveexp);
      // System.out.println("move stmt end");
      isexpcall = false;
      return _ret;
   }

   /**
    * f0 -> "PRINT"
    * f1 -> SimpleExp()
    */
   public R visit(PrintStmt n) {
      R _ret=null;
      n.f0.accept(this);
      R expr1 = n.f1.accept(this);
      _ret = (R)("PRINT " + expr1 + "\n");
      return _ret;
   }

   /**
    * f0 -> Call()
    *       | HAllocate()
    *       | BinOp()
    *       | SimpleExp()
    */
   public R visit(Exp n) {
      R _ret=null;
      return n.f0.accept(this);
   }

   /**
    * f0 -> "BEGIN"
    * f1 -> StmtList()
    * f2 -> "RETURN"
    * f3 -> SimpleExp()
    * f4 -> "END"
    */
   public R visit(StmtExp n) {
      R _ret=null;
      n.f0.accept(this);
      R stmtlist = n.f1.accept(this);
      n.f2.accept(this);
      prerequisites = "";
      R expr1 = n.f3.accept(this);
      n.f4.accept(this);
      _ret = (R)(stmtlist.toString() + "\n" +  prerequisites + "\n  MOVE v0 " + expr1.toString());
      prerequisites = "";
      return _ret;
   }

   /**
    * f0 -> "CALL"
    * f1 -> SimpleExp()
    * f2 -> "("
    * f3 -> ( Temp() )*
    * f4 -> ")"
    */
   public R visit(Call n) {
      // System.out.println("call start");
      isexpcall = true;
      FuncStackinfo f = finalinfo.tempinfo.get(currfunlabel);
      
      R _ret=null;
      n.f0.accept(this);
      incallfunc = true;
      R expr1 = n.f1.accept(this);
      incallfunc = false;
      int size = f.tmappings.size();
      for(int i=0;i<10;i++){
         prerequisites += ("ASTORE  SPILLEDARG  " + Integer.toString(f.tmappings.get(i)) + " t" + i + "\n "  );
      }
      n.f2.accept(this);
      incallargtemps = true;
      n.f3.accept(this);
      incallargtemps = false;
      n.f4.accept(this);
      String callerrestore = new String();
       for(int i=0;i<10;i++){
         callerrestore += ("ALOAD  t" + i + " SPILLEDARG  " + Integer.toString(f.tmappings.get(i))+  "\n "  );
      }
      callerrestore += ("MOVE " +returncalltemp + "  v0");
      prerequisites+=lastprerequisite;
      lastprerequisite = "";
      // System.out.println(123);

      _ret = (R)("CALL " + expr1.toString() + "\n" + callerrestore  );
      argcounter = 0;
      // System.out.println("call end");
      returncalltemp = "";
      return _ret;
   }

   /**
    * f0 -> "HALLOCATE"
    * f1 -> SimpleExp()
    */
   public R visit(HAllocate n) {
      R _ret=null;
      n.f0.accept(this);
      // v1 = true;
      R expr1 = n.f1.accept(this);
      // String p = expr1.toString();
      // if(p.startsWith("s")||p.startsWith("t")){
         // prerequisites+= ("MOVE " + p + "  PLUS " + p  + " 4 \n ");
      // }
      
      // v1 = false;
      _ret = ( R)("HALLOCATE  " + expr1.toString() + "\n");
      // _ret = ( R)("HALLOCATE  v0 " + "\n");

      return _ret;
   }

   /**
    * f0 -> Operator()
    * f1 -> Temp()
    * f2 -> SimpleExp()
    */
   public R visit(BinOp n) {
      R _ret=null;
      R operator = n.f0.accept(this);
      R temp1 = n.f1.accept(this);
      v1 = true;
      R temp2 = n.f2.accept(this);
      v1 = false;
      _ret = (R)(operator.toString() + "  " + temp1 + " " + temp2 + "\n");
      return _ret;
   }

   /**
    * f0 -> "LE"
    *       | "NE"
    *       | "PLUS"
    *       | "MINUS"
    *       | "TIMES"
    *       | "DIV"
    */
   public R visit(Operator n) {
      R _ret=null;
       NodeToken token = (NodeToken)n.f0.choice;
      String operator = token.tokenImage;
      _ret = (R)(operator);
      return _ret;
   }

   /**
    * f0 -> Temp()
    *       | IntegerLiteral()
    *       | Label()
    */
   public R visit(SimpleExp n) {
      R _ret=null;
      return n.f0.accept(this);
   }

   /**
    * f0 -> "TEMP"
    * f1 -> IntegerLiteral()
    */
   public R visit(Temp n) {
      R _ret=null;
      n.f0.accept(this);
      int  tempintliteral = Integer.valueOf(n.f1.accept(this).toString());
      String correspondingtemp = new String();
      RegAllocMap r = finalinfo.regallocinfo.get(currfunlabel);
      if(tempintliteral<=3||tempintliteral>=finalinfo.fun_argcnt.get(currfunlabel)){
         //TEMP x (0-3) || TEMP x (>argcnt)
      if(r.spilledvars.contains(tempintliteral)){
         if(v1){
            correspondingtemp = "v1";
         }else{
            correspondingtemp = "v0";
         }
         FuncStackinfo f = finalinfo.tempinfo.get(currfunlabel);
         if(!f.spilledreginfo.containsKey(tempintliteral)){
            int presetstckcnt = f.stackcount;
            finalinfo.tempinfo.get(currfunlabel).spilledreginfo.put(tempintliteral,presetstckcnt);
            finalinfo.tempinfo.get(currfunlabel).stackcount++;
         }
         int stackloc = finalinfo.tempinfo.get(currfunlabel).spilledreginfo.get(tempintliteral);
         if(inmovefirst){
            isspilled = true;
            movefirstcorrespondence = stackloc;
         }
         if(!incallfunc){
         if(!inmovefirst){
         prerequisites+= ("ALOAD  " + correspondingtemp + " SPILLEDARG " + Integer.toString(stackloc) + "\n");
         }
         }else{
         lastprerequisite+= ("ALOAD  " + correspondingtemp + " SPILLEDARG " + Integer.toString(stackloc) + "\n");

         }
         
      }else{
        if(r.smapping.containsKey(tempintliteral)){
         int p = r.smapping.get(tempintliteral);
         correspondingtemp=("s"+ Integer.toString(p));
        }else{
         int p = r.tmapping.get(tempintliteral);
         correspondingtemp=("t"+ Integer.toString(p));
        }
      }
   }
   else{
     if(v1){
            correspondingtemp = "v1";
         }else{
            correspondingtemp = "v0";
         }
      if(inmovefirst){
         isspilled = true;
         movefirstcorrespondence = tempintliteral -4;
      }
      if(!incallfunc){
      if(!inmovefirst){
      prerequisites+=("ALOAD " + correspondingtemp + " SPILLEDARG  " + Integer.toString(tempintliteral-4) + "\n" );
      }
      }else{
      lastprerequisite+=("ALOAD " + correspondingtemp + " SPILLEDARG  " + Integer.toString(tempintliteral-4) + "\n" );

      }
   }
      if(incallargtemps){
         if(argcounter<4){
        prerequisites += ("MOVE a" + Integer.toString(argcounter) + " " + correspondingtemp + "\n");
         }else{
        prerequisites += ("PASSARG " + Integer.toString(argcounter-3) + " " + correspondingtemp + "\n");
         }
         argcounter++;
      }else{
       _ret = (R)(correspondingtemp);
      }
      
      return _ret;
   }

   /**
    * f0 -> <INTEGER_LITERAL>
    */
   public R visit(IntegerLiteral n) {
      R _ret=null;
      n.f0.accept(this);
      _ret = (R)(n.f0.toString());
      return _ret;
   }

   /**
    * f0 -> <IDENTIFIER>
    */
   public R visit(Label n) {
      R _ret=null;
      n.f0.accept(this);
      _ret = (R)(n.f0.toString());
      return _ret;
   }

}
