//
// Generated by JTB 1.3.2
//

package visitor;
import syntaxtree.*;
import java.util.*;
import java.util.function.Function;

/**
 * Provides default methods which visit each node in the tree in depth-first
 * order.  Your visitors may extend this class.
 */


public class DepthFirstVisitor implements Visitor {
     public Map<String,Classinfo> classesinfoMap = new HashMap<>();

      boolean infunction = false;
      public String currclass = null ;
      Classinfo currclassinfo = null;
      Functioninfo currfuninfo = null;
      Varinfo currvarinfo = null;
      NewLambdaType currLambdaTypeInfo = null;
      public String extendedclass = null;
      boolean intype =false;
      boolean imported = false;
      String curr_lambda_rettype = new String();
      String curr_lambda_argtype = new String();

      public String currtype = null;
   public boolean is_child(String child, String parent){
      if(child.equals(parent)){
         return  true;
      }
      Classinfo c = classesinfoMap.get(child);
      while(c.parent != null){
         if(c.parent.equals(parent)){
            return true;
         }
         c = classesinfoMap.get(c.parent);
      }
      return false;
   }
   boolean check_lambda_equiv(Vector<NewLambdaType> parent_lambda_info,Vector<NewLambdaType> child_lambda_info){
           int plen = parent_lambda_info.size(),clen=child_lambda_info.size();
           if(plen!=clen){
            System.out.println("Type error");
            System.exit(0);
           }
             for(int i=0;i<plen;i++){
                if(!(parent_lambda_info.get(i)).equals(child_lambda_info)){
                  System.out.println("Type error");
                  System.exit(0);
                }
             }
             return true;
           
   }
   boolean check_parameters_equivalence(Vector<String> paramtypes,Vector<String> calltypes){
      if(paramtypes.size()!=calltypes.size()){
         System.out.println("Type error");
         System.exit(0);
      }else{
         for(int i=0;i<paramtypes.size();i++){
            if( !is_child(calltypes.get(i),paramtypes.get(i)) ){
               System.out.println("Type error");
               System.exit(0);
            }
         }
      }
      return true;
   }
   
   //
   // Auto class visitors--probably don't need to be overridden.
   //
   public void visit(NodeList n) {
      for ( Enumeration<Node> e = n.elements(); e.hasMoreElements(); )
         e.nextElement().accept(this);
   }

   public void visit(NodeListOptional n) {
      if ( n.present() )
         for ( Enumeration<Node> e = n.elements(); e.hasMoreElements(); )
            e.nextElement().accept(this);
   }

   public void visit(NodeOptional n) {
      if ( n.present() )
         n.node.accept(this);
   }

   public void visit(NodeSequence n) {
      for ( Enumeration<Node> e = n.elements(); e.hasMoreElements(); )
         e.nextElement().accept(this);
   }

   public void visit(NodeToken n) { }

   //
   // User-generated visitor methods below
   //

   /**
    * f0 -> ( ImportFunction() )?
    * f1 -> MainClass()
    * f2 -> ( TypeDeclaration() )*
    * f3 -> <EOF>
    */
   public void visit(Goal n) {
      n.f0.accept(this);
      n.f1.accept(this);
      n.f2.accept(this);
      n.f3.accept(this);
   }

   /**
    * f0 -> "import"
    * f1 -> "java.util.function.Function"
    * f2 -> ";"
    */
   public void visit(ImportFunction n) {
      n.f0.accept(this);
      n.f1.accept(this);
      n.f2.accept(this);
      imported = true;
   }

   /**
    * f0 -> "class"
    * f1 -> Identifier()
    * f2 -> "{"
    * f3 -> "public"
    * f4 -> "static"
    * f5 -> "void"
    * f6 -> "main"
    * f7 -> "("
    * f8 -> "String"
    * f9 -> "["
    * f10 -> "]"
    * f11 -> Identifier()
    * f12 -> ")"
    * f13 -> "{"
    * f14 -> PrintStatement()
    * f15 -> "}"
    * f16 -> "}"
    */
   public void visit(MainClass n) {
      n.f0.accept(this);
      n.f1.accept(this);
      // classeslist.add(n.f1.f0.toString());
      currclass = n.f1.f0.toString();
      currclassinfo = new Classinfo(currclass);
      n.f2.accept(this);
      n.f3.accept(this);
      n.f4.accept(this);
      n.f5.accept(this);
      n.f6.accept(this);
      n.f7.accept(this);
      n.f8.accept(this);
      n.f9.accept(this);
      n.f10.accept(this);
      n.f11.accept(this);
      n.f12.accept(this);
      currfuninfo = new Functioninfo("void","main",n.f11.f0.toString());
      currclassinfo.class_funcinfo.put(currfuninfo.name,currfuninfo);
      classesinfoMap.put(currclass,currclassinfo);

      n.f13.accept(this);
      n.f14.accept(this);
      n.f15.accept(this);
      n.f16.accept(this);
      currclass = null;
      currclassinfo = null;
      currfuninfo = null;
   }

   /**
    * f0 -> ClassDeclaration()
    *       | ClassExtendsDeclaration()
    */
   public void visit(TypeDeclaration n) {
      n.f0.accept(this);
   }

   /**
    * f0 -> "class"
    * f1 -> Identifier()
    * f2 -> "{"
    * f3 -> ( VarDeclaration() )*
    * f4 -> ( MethodDeclaration() )*
    * f5 -> "}"
    */
   public void visit(ClassDeclaration n) {
      n.f0.accept(this);
      n.f1.accept(this);
      currclass = n.f1.f0.toString();
      currclassinfo = new Classinfo(currclass);
      classesinfoMap.put(currclass,currclassinfo);
      n.f2.accept(this);
      n.f3.accept(this);
      n.f4.accept(this);
      n.f5.accept(this);
      currclass = null;
      currclassinfo = null;
   }

   /**
    * f0 -> "class"
    * f1 -> Identifier()
    * f2 -> "extends"
    * f3 -> Identifier()
    * f4 -> "{"
    * f5 -> ( VarDeclaration() )*
    * f6 -> ( MethodDeclaration() )*
    * f7 -> "}"
    */
   public void visit(ClassExtendsDeclaration n) {
      n.f0.accept(this);
      n.f1.accept(this);
      currclass = n.f1.f0.toString();
      n.f2.accept(this);
      n.f3.accept(this);
      extendedclass = n.f3.f0.toString();
      currclassinfo = new Classinfo(currclass,classesinfoMap.get(extendedclass));
      currclassinfo.parent = extendedclass;
      classesinfoMap.put(currclass,currclassinfo);
      n.f4.accept(this);
      n.f5.accept(this);
      n.f6.accept(this);
      n.f7.accept(this);
      currclass = null;
      extendedclass = null;
      currclassinfo = null;
   }

   /**
    * f0 -> Type()
    * f1 -> Identifier()
    * f2 -> ";"
    */
   public void visit(VarDeclaration n) {
      n.f0.accept(this);
      n.f1.accept(this);
      if(currtype.equals("Lambda")){
         currLambdaTypeInfo = new NewLambdaType(curr_lambda_argtype, curr_lambda_rettype);
         if(!infunction){
            currclassinfo.class_lambdavarinfo.put(n.f1.f0.toString(),currLambdaTypeInfo);
         }else{
            currclassinfo.class_funcinfo.get(currfuninfo.name).func_lambdavarinfo.put(n.f1.f0.toString(),currLambdaTypeInfo);
         }
      }else{
      currvarinfo = new Varinfo(currtype,n.f1.f0.toString());
      if(!infunction){
      currclassinfo.class_varinfo.put(currvarinfo.name,currvarinfo);
   }else{
      currclassinfo.class_funcinfo.get(currfuninfo.name).func_varinfo.put(currvarinfo.name,currvarinfo);
   }
}
      n.f2.accept(this);
      currvarinfo = null;
      curr_lambda_argtype=null;
      curr_lambda_rettype=null;
   }

   /**
    * f0 -> "public"
    * f1 -> Type()
    * f2 -> Identifier()
    * f3 -> "("
    * f4 -> ( FormalParameterList() )?
    * f5 -> ")"
    * f6 -> "{"
    * f7 -> ( VarDeclaration() )*
    * f8 -> ( Statement() )*
    * f9 -> "return"
    * f10 -> Expression()
    * f11 -> ";"
    * f12 -> "}"
    */
   public void visit(MethodDeclaration n) {
      infunction = true;
      n.f0.accept(this);
      n.f1.accept(this);
      n.f2.accept(this);
      String s1 = currtype,s2 = n.f2.f0.toString();
      currfuninfo = new Functioninfo(s1,s2);
      

      n.f3.accept(this);
      n.f4.accept(this);
      if(currclassinfo.parent ==null){
          currclassinfo.class_funcinfo.put(currfuninfo.name,currfuninfo);  
         }else{
            if(!classesinfoMap.get(currclassinfo.parent).class_funcinfo.containsKey(currfuninfo.name)){
               currclassinfo.class_funcinfo.put(currfuninfo.name,currfuninfo);  
            }else{
               Functioninfo parentfuninfo = classesinfoMap.get(currclassinfo.parent).class_funcinfo.get(currfuninfo.name);
               if(!parentfuninfo.rettype.equals(currfuninfo.rettype)){
                  System.out.println("Type error");
                  System.exit(0);
               }else{
                   if(check_parameters_equivalence(parentfuninfo.func_paramtype,currfuninfo.func_paramtype)&&check_lambda_equiv(parentfuninfo.lambda_param,currfuninfo.lambda_param)){
                        currclassinfo.class_funcinfo.put(currfuninfo.name,currfuninfo);
                   }
               }
            }
      }
      n.f5.accept(this);
      n.f6.accept(this);
      n.f7.accept(this);
      n.f8.accept(this);
      n.f9.accept(this);
      n.f10.accept(this);
      n.f11.accept(this);
      n.f12.accept(this);
      infunction = false;
      currfuninfo=null;
   }

   /**
    * f0 -> FormalParameter()
    * f1 -> ( FormalParameterRest() )*
    */
   public void visit(FormalParameterList n) {
      n.f0.accept(this);
      n.f1.accept(this);
   }

   /**
    * f0 -> Type()
    * f1 -> Identifier()
    */
   public void visit(FormalParameter n) {

      n.f0.accept(this);

      n.f1.accept(this);
      String s1 = currtype,s2 = n.f1.f0.toString();
      if(s1.equals("Lambda")){
        currLambdaTypeInfo = new NewLambdaType(curr_lambda_argtype,curr_lambda_rettype);
        currfuninfo.lambda_param.add(currLambdaTypeInfo);
        currfuninfo.lambda_param_names.add(s2);
        curr_lambda_argtype = null;
        curr_lambda_rettype = null;
        currLambdaTypeInfo = null;
      }else{
      currvarinfo = new Varinfo(s1,s2);
      currfuninfo.func_param.add(currvarinfo);
      currfuninfo.func_paramname.add(currvarinfo.name);
      currfuninfo.func_paramtype.add(currvarinfo.type);
      currvarinfo = null;
      }
   }

   /**
    * f0 -> ","
    * f1 -> FormalParameter()
    */
   public void visit(FormalParameterRest n) {
      n.f0.accept(this);
      n.f1.accept(this);
   }

   /**
    * f0 -> ArrayType()
    *       | BooleanType()
    *       | IntegerType()
    *       | Identifier()
    *       | LambdaType()
    */
   public void visit(Type n) {
      intype=true;
      n.f0.accept(this);
      intype=false;
   }

   /**
    * f0 -> "int"
    * f1 -> "["
    * f2 -> "]"
    */
   public void visit(ArrayType n) {
      n.f0.accept(this);
      n.f1.accept(this);
      n.f2.accept(this);
      currtype = "int[]";
   }

   /**
    * f0 -> "boolean"
    */
   public void visit(BooleanType n) {
      n.f0.accept(this);
      currtype = "boolean";
   }

   /**
    * f0 -> "int"
    */
   public void visit(IntegerType n) {
      n.f0.accept(this);
      currtype = "int";
   }

   /**
    * f0 -> "Function"
    * f1 -> "<"
    * f2 -> Identifier()
    * f3 -> ","
    * f4 -> Identifier()
    * f5 -> ">"
    */
   public void visit(LambdaType n) {
      if(!imported){
         System.out.println("Symbol not found");
         System.exit(0);
      }
      n.f0.accept(this);
      n.f1.accept(this);
      n.f2.accept(this);
      curr_lambda_argtype = n.f2.f0.toString();
      n.f3.accept(this);
      n.f4.accept(this);
      curr_lambda_rettype = n.f4.f0.toString();
      if(curr_lambda_argtype==null||curr_lambda_rettype==null){
         System.out.println("Type error");
         System.exit(0);
      }
      if(curr_lambda_argtype.equals("Integer")){
         curr_lambda_argtype = "int";
      }else if(curr_lambda_argtype.equals("Boolean")){
         curr_lambda_argtype = "boolean";
      }
      if(curr_lambda_rettype.equals("Integer")){
         curr_lambda_rettype = "int";
      }else if(curr_lambda_rettype.equals("Boolean")){
         curr_lambda_rettype = "boolean";
      }
      n.f5.accept(this);
      currtype = "Lambda";
   }

   /**
    * f0 -> Block()
    *       | AssignmentStatement()
    *       | ArrayAssignmentStatement()
    *       | IfStatement()
    *       | WhileStatement()
    *       | PrintStatement()
    */
   public void visit(Statement n) {
      n.f0.accept(this);
   }

   /**
    * f0 -> "{"
    * f1 -> ( Statement() )*
    * f2 -> "}"
    */
   public void visit(Block n) {
      n.f0.accept(this);
      n.f1.accept(this);
      n.f2.accept(this);
   }

   /**
    * f0 -> Identifier()
    * f1 -> "="
    * f2 -> Expression()
    * f3 -> ";"
    */
   public void visit(AssignmentStatement n) {
      n.f0.accept(this);
      n.f1.accept(this);
      n.f2.accept(this);
      n.f3.accept(this);
   }

   /**
    * f0 -> Identifier()
    * f1 -> "["
    * f2 -> Expression()
    * f3 -> "]"
    * f4 -> "="
    * f5 -> Expression()
    * f6 -> ";"
    */
   public void visit(ArrayAssignmentStatement n) {
      n.f0.accept(this);
      n.f1.accept(this);
      n.f2.accept(this);
      n.f3.accept(this);
      n.f4.accept(this);
      n.f5.accept(this);
      n.f6.accept(this);
   }

   /**
    * f0 -> IfthenElseStatement()
    *       | IfthenStatement()
    */
   public void visit(IfStatement n) {
      n.f0.accept(this);
   }

   /**
    * f0 -> "if"
    * f1 -> "("
    * f2 -> Expression()
    * f3 -> ")"
    * f4 -> Statement()
    */
   public void visit(IfthenStatement n) {
      n.f0.accept(this);
      n.f1.accept(this);
      n.f2.accept(this);
      n.f3.accept(this);
      n.f4.accept(this);
   }

   /**
    * f0 -> "if"
    * f1 -> "("
    * f2 -> Expression()
    * f3 -> ")"
    * f4 -> Statement()
    * f5 -> "else"
    * f6 -> Statement()
    */
   public void visit(IfthenElseStatement n) {
      n.f0.accept(this);
      n.f1.accept(this);
      n.f2.accept(this);
      n.f3.accept(this);
      n.f4.accept(this);
      n.f5.accept(this);
      n.f6.accept(this);
   }

   /**
    * f0 -> "while"
    * f1 -> "("
    * f2 -> Expression()
    * f3 -> ")"
    * f4 -> Statement()
    */
   public void visit(WhileStatement n) {
      n.f0.accept(this);
      n.f1.accept(this);
      n.f2.accept(this);
      n.f3.accept(this);
      n.f4.accept(this);
   }

   /**
    * f0 -> "System.out.println"
    * f1 -> "("
    * f2 -> Expression()
    * f3 -> ")"
    * f4 -> ";"
    */
   public void visit(PrintStatement n) {
      n.f0.accept(this);
      n.f1.accept(this);
      n.f2.accept(this);
      n.f3.accept(this);
      n.f4.accept(this);
   }

   /**
    * f0 -> OrExpression()
    *       | AndExpression()
    *       | CompareExpression()
    *       | neqExpression()
    *       | AddExpression()
    *       | MinusExpression()
    *       | TimesExpression()
    *       | DivExpression()
    *       | ArrayLookup()
    *       | ArrayLength()
    *       | MessageSend()
    *       | LambdaExpression()
    *       | PrimaryExpression()
    */
   public void visit(Expression n) {
      n.f0.accept(this);
   }

   /**
    * f0 -> "("
    * f1 -> Identifier()
    * f2 -> ")"
    * f3 -> "->"
    * f4 -> Expression()
    */
   public void visit(LambdaExpression n) {
      n.f0.accept(this);
      n.f1.accept(this);
      n.f2.accept(this);
      n.f3.accept(this);
      n.f4.accept(this);
   }

   /**
    * f0 -> PrimaryExpression()
    * f1 -> "&&"
    * f2 -> PrimaryExpression()
    */
   public void visit(AndExpression n) {
      n.f0.accept(this);
      n.f1.accept(this);
      n.f2.accept(this);
   }

   /**
    * f0 -> PrimaryExpression()
    * f1 -> "||"
    * f2 -> PrimaryExpression()
    */
   public void visit(OrExpression n) {
      n.f0.accept(this);
      n.f1.accept(this);
      n.f2.accept(this);
   }

   /**
    * f0 -> PrimaryExpression()
    * f1 -> "<="
    * f2 -> PrimaryExpression()
    */
   public void visit(CompareExpression n) {
      n.f0.accept(this);
      n.f1.accept(this);
      n.f2.accept(this);
   }

   /**
    * f0 -> PrimaryExpression()
    * f1 -> "!="
    * f2 -> PrimaryExpression()
    */
   public void visit(neqExpression n) {
      n.f0.accept(this);
      n.f1.accept(this);
      n.f2.accept(this);
   }

   /**
    * f0 -> PrimaryExpression()
    * f1 -> "+"
    * f2 -> PrimaryExpression()
    */
   public void visit(AddExpression n) {
      n.f0.accept(this);
      n.f1.accept(this);
      n.f2.accept(this);
   }

   /**
    * f0 -> PrimaryExpression()
    * f1 -> "-"
    * f2 -> PrimaryExpression()
    */
   public void visit(MinusExpression n) {
      n.f0.accept(this);
      n.f1.accept(this);
      n.f2.accept(this);
   }

   /**
    * f0 -> PrimaryExpression()
    * f1 -> "*"
    * f2 -> PrimaryExpression()
    */
   public void visit(TimesExpression n) {
      n.f0.accept(this);
      n.f1.accept(this);
      n.f2.accept(this);
   }

   /**
    * f0 -> PrimaryExpression()
    * f1 -> "/"
    * f2 -> PrimaryExpression()
    */
   public void visit(DivExpression n) {
      n.f0.accept(this);
      n.f1.accept(this);
      n.f2.accept(this);
   }

   /**
    * f0 -> PrimaryExpression()
    * f1 -> "["
    * f2 -> PrimaryExpression()
    * f3 -> "]"
    */
   public void visit(ArrayLookup n) {
      n.f0.accept(this);
      n.f1.accept(this);
      n.f2.accept(this);
      n.f3.accept(this);
   }

   /**
    * f0 -> PrimaryExpression()
    * f1 -> "."
    * f2 -> "length"
    */
   public void visit(ArrayLength n) {
      n.f0.accept(this);
      n.f1.accept(this);
      n.f2.accept(this);
   }

   /**
    * f0 -> PrimaryExpression()
    * f1 -> "."
    * f2 -> Identifier()
    * f3 -> "("
    * f4 -> ( ExpressionList() )?
    * f5 -> ")"
    */
   public void visit(MessageSend n) {
      n.f0.accept(this);
      n.f1.accept(this);
      n.f2.accept(this);
      n.f3.accept(this);
      n.f4.accept(this);
      n.f5.accept(this);
      

   }

   /**
    * f0 -> Expression()
    * f1 -> ( ExpressionRest() )*
    */
   public void visit(ExpressionList n) {
      n.f0.accept(this);
      n.f1.accept(this);
   }

   /**
    * f0 -> ","
    * f1 -> Expression()
    */
   public void visit(ExpressionRest n) {
      n.f0.accept(this);
      n.f1.accept(this);
   }

   /**
    * f0 -> IntegerLiteral()
    *       | TrueLiteral()
    *       | FalseLiteral()
    *       | Identifier()
    *       | ThisExpression()
    *       | ArrayAllocationExpression()
    *       | AllocationExpression()
    *       | NotExpression()
    *       | BracketExpression()
    */
   public void visit(PrimaryExpression n) {
      n.f0.accept(this);
   }

   /**
    * f0 -> <INTEGER_LITERAL>
    */
   public void visit(IntegerLiteral n) {
      n.f0.accept(this);
   }

   /**
    * f0 -> "true"
    */
   public void visit(TrueLiteral n) {
      n.f0.accept(this);
   }

   /**
    * f0 -> "false"
    */
   public void visit(FalseLiteral n) {
      n.f0.accept(this);
   }

   /**
    * f0 -> <IDENTIFIER>
    */
   public void visit(Identifier n) {
      n.f0.accept(this);
      if(intype){
      currtype = n.f0.toString();
      }
   }

   /**
    * f0 -> "this"
    */
   public void visit(ThisExpression n) {
      n.f0.accept(this);
   }

   /**
    * f0 -> "new"
    * f1 -> "int"
    * f2 -> "["
    * f3 -> Expression()
    * f4 -> "]"
    */
   public void visit(ArrayAllocationExpression n) {
      n.f0.accept(this);
      n.f1.accept(this);
      n.f2.accept(this);
      n.f3.accept(this);
      n.f4.accept(this);
   }

   /**
    * f0 -> "new"
    * f1 -> Identifier()
    * f2 -> "("
    * f3 -> ")"
    */
   public void visit(AllocationExpression n) {
      n.f0.accept(this);
      n.f1.accept(this);
      n.f2.accept(this);
      n.f3.accept(this);
   }

   /**
    * f0 -> "!"
    * f1 -> Expression()
    */
   public void visit(NotExpression n) {
      n.f0.accept(this);
      n.f1.accept(this);
   }

   /**
    * f0 -> "("
    * f1 -> Expression()
    * f2 -> ")"
    */
   public void visit(BracketExpression n) {
      n.f0.accept(this);
      n.f1.accept(this);
      n.f2.accept(this);
   }

}
