//
// Generated by JTB 1.3.2
//

package visitor;
import syntaxtree.*;
import java.util.*;

/**
 * Provides default methods which visit each node in the tree in depth-first
 * order.  Your visitors may extend this class.
 */
public class GJDepthFirst<R,A> implements GJVisitor<R,A> {
   // Map<String,Vector<Vector<String>>> classVar = new HashMap<>();
   // Map<String,Vector<Vector<String>>> methodVar = new HashMap<>();
   // Map<String,Vector<Vector<String>>> classMethod = new HashMap<>();
   // Map<String,Vector<Vector<String>>> FuncParList = new HashMap<>();
   // Map<String,Vector<String>> classFunccallList= new HashMap<>();
   // Set<String> classeslist = new HashSet<>();
   // boolean imported = false;
   public Map<String,Classinfo> classesinfoMap = new HashMap<>();

   String currclass = null;
   String currmthdname = null;
   String varname = null;
   String vartype = null;
   Classinfo currclassinfo = null;
   Functioninfo currfuninfo = null;
   Varinfo currvarinfo = null;
   String currfuncallname= null;
   String currclasscall = null;
   Vector<String> currfunccalltypes = new Vector<String>();
   boolean inmain = false;
   boolean inmessage = false;
   boolean temp= true;
   String curr_lambda_name = null;
   NewLambdaType curr_lambda_info = null;
   String extra_arg = new String();
   boolean in_lambda_expression = false;
   boolean in_lambda_argument = false;
   boolean in_lambda_info = false;

   R INT_R = (R) "int";
   R BOOLEAN_R = (R) "boolean";
   R INT_ARRAY_R = (R) "int[]";
   R TRUE_R = (R) "true";
   R FALSE_R = (R) "false";
   R LAMBDA_R = (R) "Lambda";



   public GJDepthFirst(Map<String,Classinfo> classesinfoMap) {
      this.classesinfoMap = classesinfoMap;
   }
    public R checklambdastrings(String l,String r){
      String[] p1 = l.trim().split("\\s+");
      String[] p2 = r.trim().split("\\s+");
      String l1 = p1[p1.length-2],l2= p2[p2.length-1];
      if(l1.equals(l2)){
         return TRUE_R;
      }
      
      return FALSE_R;

    }
   public R is_child(String child, String parent){
      if(child.equals(parent)){
         return TRUE_R;
      }
      Classinfo c = classesinfoMap.get(child);
      while(c.parent != null){
         if(c.parent.equals(parent)){
            return TRUE_R;
         }
         c = classesinfoMap.get(c.parent);
      }
      return FALSE_R;
   }

   public R check_declaration_error(String x,Classinfo currclassinfo1,Functioninfo currfuninfo1){
          R vartype = null;
      if(currfuninfo1!=null&&currfuninfo1.func_lambdavarinfo.containsKey(x)){
         NewLambdaType n1= currfuninfo1.func_lambdavarinfo.get(x);
         vartype = (R)("< " + n1.argtype + " " + n1.rettype + " >" );
         return vartype;
      }else if(currclassinfo1!=null&&currclassinfo1.class_lambdavarinfo.containsKey(x)){
         NewLambdaType n1= currclassinfo1.class_lambdavarinfo.get(x);
         vartype = (R)("< " + n1.argtype + " " + n1.rettype + " >" );
         return vartype;
      }
      if(currfuninfo1!=null&& currfuninfo1.func_varinfo.containsKey(x)){
         vartype = (R) currfuninfo1.func_varinfo.get(x).type;
      }else{
          if(currfuninfo1!=null && currfuninfo1.func_paramname.contains(x)){
               int index = currfuninfo1.func_paramname.indexOf(x);
               vartype = (R) currfuninfo1.func_param.get(index).type;
            }
        else{
          if(currclassinfo1!=null &&currclassinfo1.class_varinfo.containsKey(x)){
            vartype = (R) currclassinfo1.class_varinfo.get(x).type;
         }else{
            if(currclassinfo1!=null&&currclassinfo1.class_funcinfo.containsKey(x)){
               vartype = (R) currclassinfo1.class_funcinfo.get(x).rettype;
            }else{
            if(classesinfoMap.containsKey(x)){
               vartype = (R) classesinfoMap.get(x).name;
            }else{
            System.out.println("Symbol not found");
            System.exit(0);
            }
            }
          }
         }
      }
      return vartype;
   }
   public R check_func_call(String classname,String funcname,Vector<String> calltypes){
      Classinfo c = classesinfoMap.get(classname);
      boolean typerror= false;
      while(c!=null){
         if(c.class_funcinfo.containsKey(funcname)){
            Functioninfo f = c.class_funcinfo.get(funcname);
            if(f.func_paramtype.size()==calltypes.size()){
               for(int i=0;i<calltypes.size();i++){
                  if(!is_child(calltypes.get(i),f.func_paramtype.get(i)).equals(TRUE_R)){
                     typerror = true;
                  }
               }
               if(!typerror){
                  return (R) f.rettype;
               }

            }else{
               typerror = true;
            }
          c = classesinfoMap.get(c.parent);

         }else{
               c = classesinfoMap.get(c.parent);
         }
      }
         if(!typerror){
         System.out.println("Symbol not found");
         }else{
         System.out.println("Type error");
         }
         System.exit(0);
      return null;
   }
   // Auto class visitors--probably don't need to be overridden.
   //
   public R visit(NodeList n, A argu) {
      R _ret=null;
      int _count=0;
      for ( Enumeration<Node> e = n.elements(); e.hasMoreElements(); ) {
         e.nextElement().accept(this,argu);
         _count++;
      }
      return _ret;
   }

   public R visit(NodeListOptional n, A argu) {
      if ( n.present() ) {
         R _ret=null;
         int _count=0;
         for ( Enumeration<Node> e = n.elements(); e.hasMoreElements(); ) {
            e.nextElement().accept(this,argu);
            _count++;
         }
         return _ret;
      }
      else
         return null;
   }

   public R visit(NodeOptional n, A argu) {
      if ( n.present() )
         return n.node.accept(this,argu);
      else
         return null;
   }

   public R visit(NodeSequence n, A argu) {
      R _ret=null;
      int _count=0;
      for ( Enumeration<Node> e = n.elements(); e.hasMoreElements(); ) {
         e.nextElement().accept(this,argu);
         _count++;
      }
      return _ret;
   }

   public R visit(NodeToken n, A argu) { return null; }

   //
   // User-generated visitor methods below
   //

   /**
    * f0 -> ( ImportFunction() )?
    * f1 -> MainClass()
    * f2 -> ( TypeDeclaration() )*
    * f3 -> <EOF>
    */
   public R visit(Goal n, A argu) {
      R _ret=null;
      n.f0.accept(this, argu);
      n.f1.accept(this, argu);
      n.f2.accept(this, argu);
      n.f3.accept(this, argu);
      return _ret;
   }

   /**
    * f0 -> "import"
    * f1 -> "java.util.function.Function"
    * f2 -> ";"
    */
   public R visit(ImportFunction n, A argu) {
      R _ret=null;
      n.f0.accept(this, argu);
      n.f1.accept(this, argu);
      n.f2.accept(this, argu);
      return _ret;
   }

   /**
    * f0 -> "class"
    * f1 -> Identifier()
    * f2 -> "{"
    * f3 -> "public"
    * f4 -> "static"
    * f5 -> "void"
    * f6 -> "main"
    * f7 -> "("
    * f8 -> "String"
    * f9 -> "["
    * f10 -> "]"
    * f11 -> Identifier()
    * f12 -> ")"
    * f13 -> "{"
    * f14 -> PrintStatement()
    * f15 -> "}"
    * f16 -> "}"
    */
   public R visit(MainClass n, A argu) {
      R _ret=null;
      inmain = true;
      n.f0.accept(this, argu);
      n.f1.accept(this, argu);
       currclass = n.f1.f0.toString();
      currclassinfo = classesinfoMap.get(currclass);
      n.f2.accept(this, argu);
      n.f3.accept(this, argu);
      n.f4.accept(this, argu);
      n.f5.accept(this, argu);
      n.f6.accept(this, argu);
      currfuninfo = currclassinfo.class_funcinfo.get("main");
      n.f7.accept(this, argu);
      n.f8.accept(this, argu);
      n.f9.accept(this, argu);
      n.f10.accept(this, argu);
      n.f11.accept(this, argu);
      n.f12.accept(this, argu);
      n.f13.accept(this, argu);
      n.f14.accept(this, argu);
      n.f15.accept(this, argu);
      n.f16.accept(this, argu);
      currclassinfo = null;
      currfuninfo = null;
      inmain = false;
      return _ret;
   }

   /**
    * f0 -> ClassDeclaration()
    *       | ClassExtendsDeclaration()
    */
   public R visit(TypeDeclaration n, A argu) {
      R _ret=null;
      n.f0.accept(this, argu);
      return _ret;
   }

   /**
    * f0 -> "class"
    * f1 -> Identifier()
    * f2 -> "{"
    * f3 -> ( VarDeclaration() )*
    * f4 -> ( MethodDeclaration() )*
    * f5 -> "}"
    */
   public R visit(ClassDeclaration n, A argu) {
      R _ret=null;
      n.f0.accept(this, argu);
      temp = true;
      n.f1.accept(this, argu);
      temp = false;
      currclass = n.f1.f0.toString();
      currclassinfo = classesinfoMap.get(currclass);
      n.f2.accept(this, argu);
      n.f3.accept(this, argu);
      n.f4.accept(this, argu);
      n.f5.accept(this, argu);
      currclass = null;
      currclassinfo = null;
      return _ret;
   }

   /**
    * f0 -> "class"
    * f1 -> Identifier()
    * f2 -> "extends"
    * f3 -> Identifier()
    * f4 -> "{"
    * f5 -> ( VarDeclaration() )*
    * f6 -> ( MethodDeclaration() )*
    * f7 -> "}"
    */
   public R visit(ClassExtendsDeclaration n, A argu) {
      R _ret=null;
      n.f0.accept(this, argu);
      n.f1.accept(this, argu);
      currclass = n.f1.f0.toString();
      currclassinfo = classesinfoMap.get(currclass);
      n.f2.accept(this, argu);
      n.f3.accept(this, argu);
      n.f4.accept(this, argu);
      n.f5.accept(this, argu);
      n.f6.accept(this, argu);
      n.f7.accept(this, argu);
      currclassinfo = null;
      currclass = null;
      return _ret;
   }

   /**
    * f0 -> Type()
    * f1 -> Identifier()
    * f2 -> ";"
    */
   public R visit(VarDeclaration n, A argu) {
      R _ret=null;
      n.f0.accept(this, argu);
      n.f1.accept(this, argu);
      n.f2.accept(this, argu);
      return _ret;
   }

   /**
    * f0 -> "public"
    * f1 -> Type()
    * f2 -> Identifier()
    * f3 -> "("
    * f4 -> ( FormalParameterList() )?
    * f5 -> ")"
    * f6 -> "{"
    * f7 -> ( VarDeclaration() )*
    * f8 -> ( Statement() )*
    * f9 -> "return"
    * f10 -> Expression()
    * f11 -> ";"
    * f12 -> "}"
    */
   public R visit(MethodDeclaration n, A argu) {
      R _ret=null;
      n.f0.accept(this, argu);
      n.f2.accept(this, argu);
      currfuninfo = currclassinfo.class_funcinfo.get(n.f2.f0.toString());
      R ret_type = (R) currfuninfo.rettype;
      n.f3.accept(this, argu);
      n.f4.accept(this, argu);
      n.f5.accept(this, argu);
      n.f6.accept(this, argu);
      n.f7.accept(this, argu);
      n.f8.accept(this, argu);
      n.f9.accept(this, argu);
      R exprtype = n.f10.accept(this, argu);
      if(!exprtype.equals(ret_type) ){
         System.out.println("Type error");
         System.exit(0);
      }
      n.f11.accept(this, argu);
      n.f12.accept(this, argu);
      currfuninfo = null;
      return _ret;
   }

   /**
    * f0 -> FormalParameter()
    * f1 -> ( FormalParameterRest() )*
    */
   public R visit(FormalParameterList n, A argu) {
      R _ret=null;
      n.f0.accept(this, argu);
      n.f1.accept(this, argu);
      return _ret;
   }

   /**
    * f0 -> Type()
    * f1 -> Identifier()
    */
   public R visit(FormalParameter n, A argu) {
      R _ret=null;
      n.f0.accept(this, argu);
      n.f1.accept(this, argu);
      return _ret;
   }

   /**
    * f0 -> ","
    * f1 -> FormalParameter()
    */
   public R visit(FormalParameterRest n, A argu) {
      R _ret=null;
      n.f0.accept(this, argu);
      n.f1.accept(this, argu);
      return _ret;
   }

   /**
    * f0 -> ArrayType()
    *       | BooleanType()
    *       | IntegerType()
    *       | Identifier()
    *       | LambdaType()
    */
   public R visit(Type n, A argu) {
      R _ret=null;
      n.f0.accept(this, argu);
      return _ret;
   }

   /**
    * f0 -> "int"
    * f1 -> "["
    * f2 -> "]"
    */
   public R visit(ArrayType n, A argu) {
      R _ret=null;
      n.f0.accept(this, argu);
      n.f1.accept(this, argu);
      n.f2.accept(this, argu);
      return _ret;
   }

   /**
    * f0 -> "boolean"
    */
   public R visit(BooleanType n, A argu) {
      R _ret=null;
      n.f0.accept(this, argu);
      return _ret;
   }

   /**
    * f0 -> "int"
    */
   public R visit(IntegerType n, A argu) {
      R _ret=null;
      n.f0.accept(this, argu);
      return _ret;
   }

   /**
    * f0 -> "Function"
    * f1 -> "<"
    * f2 -> Identifier()
    * f3 -> ","
    * f4 -> Identifier()
    * f5 -> ">"
    */
   public R visit(LambdaType n, A argu) {
      in_lambda_info = true;
      R _ret=null;
      n.f0.accept(this, argu);
      n.f1.accept(this, argu);
      n.f2.accept(this, argu);
      n.f3.accept(this, argu);
      n.f4.accept(this, argu);
      n.f5.accept(this, argu);
      in_lambda_info = false;
      return _ret;
   }

   /**
    * f0 -> Block()
    *       | AssignmentStatement()
    *       | ArrayAssignmentStatement()
    *       | IfStatement()
    *       | WhileStatement()
    *       | PrintStatement()
    */
   public R visit(Statement n, A argu) {
      R _ret=null;
      n.f0.accept(this, argu);
      return _ret;
   }

   /**
    * f0 -> "{"
    * f1 -> ( Statement() )*
    * f2 -> "}"
    */
   public R visit(Block n, A argu) {
      R _ret=null;
      n.f0.accept(this, argu);
      n.f1.accept(this, argu);
      n.f2.accept(this, argu);
      return _ret;
   }

   /**
    * f0 -> Identifier()
    * f1 -> "="
    * f2 -> Expression()
    * f3 -> ";"
    */
   public R visit(AssignmentStatement n, A argu) {
      R _ret=null;
      R vartype = n.f0.accept(this, argu);
      n.f1.accept(this, argu);
       String varconv= vartype.toString();
      if(varconv.charAt(0)=='<'){
        curr_lambda_name = n.f0.f0.toString();
      }
      R exprtype = n.f2.accept(this, argu);
     String exprconv = exprtype.toString();
         if((varconv.charAt(0)=='<')){
            if(checklambdastrings(varconv,exprconv).equals(FALSE_R)){
              System.out.println("Type error");
              System.exit(0);
            }
         }else{
      if(!is_child(exprtype.toString(),vartype.toString()).equals(TRUE_R)){
         System.out.println("Type error");
         System.exit(0);
      }
   }
      n.f3.accept(this, argu);
      curr_lambda_name = null;
      return _ret;
   }

   /**
    * f0 -> Identifier()
    * f1 -> "["
    * f2 -> Expression()
    * f3 -> "]"
    * f4 -> "="
    * f5 -> Expression()
    * f6 -> ";"
    */
   public R visit(ArrayAssignmentStatement n, A argu) {
      R _ret=null;
      R vartype = n.f0.accept(this, argu);
      n.f1.accept(this, argu);
      R type1 = n.f2.accept(this, argu);
      n.f3.accept(this, argu);
      n.f4.accept(this, argu);
      n.f5.accept(this, argu);
      R type2 = n.f5.accept(this, argu);
      if(!type1.equals(INT_R) || !type2.equals(INT_R) || !vartype.equals(INT_ARRAY_R)){
         System.out.println("Type error");
         System.exit(0);
      }
      n.f6.accept(this, argu);
      return _ret;
   }

   /**
    * f0 -> IfthenElseStatement()
    *       | IfthenStatement()
    */
   public R visit(IfStatement n, A argu) {
      R _ret=null;
      n.f0.accept(this, argu);
      return _ret;
   }

   /**
    * f0 -> "if"
    * f1 -> "("
    * f2 -> Expression()
    * f3 -> ")"
    * f4 -> Statement()
    */
   public R visit(IfthenStatement n, A argu) {
      R _ret=null;
      n.f0.accept(this, argu);
      n.f1.accept(this, argu);
      R type1 = n.f2.accept(this, argu);
      if(!type1.equals(BOOLEAN_R)){
         System.out.println("Type error");
         System.exit(0);
      }
      n.f3.accept(this, argu);
      n.f4.accept(this, argu);
      return _ret;
   }

   /**
    * f0 -> "if"
    * f1 -> "("
    * f2 -> Expression()
    * f3 -> ")"
    * f4 -> Statement()
    * f5 -> "else"
    * f6 -> Statement()
    */
   public R visit(IfthenElseStatement n, A argu) {
      R _ret=null;
      n.f0.accept(this, argu);
      n.f1.accept(this, argu);
      R type1 = n.f2.accept(this, argu);
      if(!type1.equals(BOOLEAN_R)){
         System.out.println("Type error");
         System.exit(0);
      }
      n.f3.accept(this, argu);
      n.f4.accept(this, argu);
      n.f5.accept(this, argu);
      n.f6.accept(this, argu);
      return _ret;
   }

   /**
    * f0 -> "while"
    * f1 -> "("
    * f2 -> Expression()
    * f3 -> ")"
    * f4 -> Statement()
    */
   public R visit(WhileStatement n, A argu) {
      R _ret=null;
      n.f0.accept(this, argu);
      n.f1.accept(this, argu);
      R type1 = n.f2.accept(this, argu);
      if(!type1.equals(BOOLEAN_R)){
         System.out.println("Type error");
         System.exit(0);
      }
      n.f3.accept(this, argu);
      n.f4.accept(this, argu);
      return _ret;
   }

   /**
    * f0 -> "System.out.println"
    * f1 -> "("
    * f2 -> Expression()
    * f3 -> ")"
    * f4 -> ";"
    */
   public R visit(PrintStatement n, A argu) {
      R _ret=null;
      n.f0.accept(this, argu);
      n.f1.accept(this, argu);
      n.f2.accept(this, argu);
      n.f3.accept(this, argu);
      n.f4.accept(this, argu);
      return _ret;
   }

   /**
    * f0 -> OrExpression()
    *       | AndExpression()
    *       | CompareExpression()
    *       | neqExpression()
    *       | AddExpression()
    *       | MinusExpression()
    *       | TimesExpression()
    *       | DivExpression()
    *       | ArrayLookup()
    *       | ArrayLength()
    *       | MessageSend()
    *       | LambdaExpression()
    *       | PrimaryExpression()
    */
   public R visit(Expression n, A argu) {
      R _ret=null;
      return n.f0.accept(this, argu);
   }

   /**
    * f0 -> "("
    * f1 -> Identifier()
    * f2 -> ")"
    * f3 -> "->"
    * f4 -> Expression()
    */
   public R visit(LambdaExpression n, A argu) {
      R _ret=null;
      if(curr_lambda_name==null){
         System.out.println("Type error");
         System.exit(0);
      }
      n.f0.accept(this, argu);
      in_lambda_argument = true;
      n.f1.accept(this, argu);
      in_lambda_argument = false;
      extra_arg = n.f1.f0.toString();
      if(extra_arg==null){
         System.out.println("Type error");
         System.exit(0);
      }
      n.f2.accept(this, argu);
      n.f3.accept(this, argu);
      in_lambda_expression = true;
      R type2=n.f4.accept(this, argu);
      in_lambda_expression = false;
      extra_arg = null;
      _ret = (R) ("!Alpha "+ type2.toString());
      return _ret;
   }

   /**
    * f0 -> PrimaryExpression()
    * f1 -> "&&"
    * f2 -> PrimaryExpression()
    */
   public R visit(AndExpression n, A argu) {
      R _ret=null;
      R type1 = n.f0.accept(this, argu);
      n.f1.accept(this, argu);
      R type2 = n.f2.accept(this, argu);
      if(!type1.equals(BOOLEAN_R) || !type2.equals(BOOLEAN_R)){
         System.out.println("Type error");
         System.exit(0);
      }else{
         _ret = BOOLEAN_R;
      }

      return _ret;
   }

   /**
    * f0 -> PrimaryExpression()
    * f1 -> "||"
    * f2 -> PrimaryExpression()
    */
   public R visit(OrExpression n, A argu) {
       R _ret=null;
      R type1 = n.f0.accept(this, argu);
      n.f1.accept(this, argu);
      R type2 = n.f2.accept(this, argu);
      if(!type1.equals(BOOLEAN_R) || !type2.equals(BOOLEAN_R)){
         System.out.println("Type error");
         System.exit(0);
      }else{
         _ret = BOOLEAN_R;
      }

      return _ret;
   }

   /**
    * f0 -> PrimaryExpression()
    * f1 -> "<="
    * f2 -> PrimaryExpression()
    */
   public R visit(CompareExpression n, A argu) {
       R _ret=null;
      R type1 = n.f0.accept(this, argu);
      n.f1.accept(this, argu);
      R type2 = n.f2.accept(this, argu);
      if(type1==null||type2==null||!type1.equals(INT_R) || !type2.equals(INT_R) ){
         System.out.println("Type error");
         System.exit(0);
      }else{
         _ret = BOOLEAN_R;
      }

      return _ret;
   }

   /**
    * f0 -> PrimaryExpression()
    * f1 -> "!="
    * f2 -> PrimaryExpression()
    */
   public R visit(neqExpression n, A argu) {
      R _ret=null;
      R type1 = n.f0.accept(this, argu);
      n.f1.accept(this, argu);
      R type2 = n.f2.accept(this, argu);
      if(!is_child(type2.toString(),type1.toString()).equals(TRUE_R)){
         System.out.println("Type error");
         System.exit(0);
      }
      _ret = BOOLEAN_R;
      return _ret;
   }

   /**
    * f0 -> PrimaryExpression()
    * f1 -> "+"
    * f2 -> PrimaryExpression()
    */
   public R visit(AddExpression n, A argu) {
      R _ret=null;
      R type1 = n.f0.accept(this, argu);
      n.f1.accept(this, argu);
      R type2 = n.f2.accept(this, argu);
      if(!type1.equals(INT_R) || !type2.equals(INT_R)){
         System.out.println("Type error");
         System.exit(0);
      }else{
         _ret = INT_R;
      }

      return _ret;
   }

   /**
    * f0 -> PrimaryExpression()
    * f1 -> "-"
    * f2 -> PrimaryExpression()
    */
   public R visit(MinusExpression n, A argu) {
      R _ret=null;
      R type1 = n.f0.accept(this, argu);
      n.f1.accept(this, argu);
      R type2 = n.f2.accept(this, argu);
      if(!type1.equals( INT_R) || !type2.equals(INT_R)){
         System.out.println("Type error");
         System.exit(0);
      }else{
         _ret = INT_R;
      }

      return _ret;
   }

   /**
    * f0 -> PrimaryExpression()
    * f1 -> "*"
    * f2 -> PrimaryExpression()
    */
   public R visit(TimesExpression n, A argu) {
     R _ret=null;
      R type1 = n.f0.accept(this, argu);
      n.f1.accept(this, argu);
      R type2 = n.f2.accept(this, argu);
      if(!type1.equals(INT_R) || !type2.equals(INT_R)){
         System.out.println("Type error");
         System.exit(0);
      }else{
         _ret = INT_R;
      }

      return _ret;
   }

   /**
    * f0 -> PrimaryExpression()
    * f1 -> "/"
    * f2 -> PrimaryExpression()
    */
   public R visit(DivExpression n, A argu) {
     R _ret=null;
      R type1 = n.f0.accept(this, argu);
      n.f1.accept(this, argu);
      R type2 = n.f2.accept(this, argu);
      if(!type1.equals(INT_R) || !type2.equals(INT_R)){
         System.out.println("Type error");
         System.exit(0);
      }else{
         _ret = INT_R;
      }

      return _ret;
   }

   /**
    * f0 -> PrimaryExpression()
    * f1 -> "["
    * f2 -> PrimaryExpression()
    * f3 -> "]"
    */
   public R visit(ArrayLookup n, A argu) {
      R _ret=null;
      R type1 = n.f0.accept(this, argu);
      n.f1.accept(this, argu);
      R type2 = n.f2.accept(this, argu);
      if(!type1.equals(INT_ARRAY_R) || !type2.equals(INT_R)){
         System.out.println("Type error");
         System.exit(0);
      }else{
         _ret = INT_R;
      }
      n.f3.accept(this, argu);
      return _ret;
   }

   /**
    * f0 -> PrimaryExpression()
    * f1 -> "."
    * f2 -> "length"
    */
   public R visit(ArrayLength n, A argu) {
      R _ret=null;
      R type1 = n.f0.accept(this, argu);
      if(!type1.equals(INT_ARRAY_R)){
         System.out.println("Type error");
         System.exit(0);
      }else{
         _ret = INT_R;     
      }
      n.f1.accept(this, argu);
      n.f2.accept(this, argu);
      return _ret;
   }

   /**
    * f0 -> PrimaryExpression()
    * f1 -> "."
    * f2 -> Identifier()
    * f3 -> "("
    * f4 -> ( ExpressionList() )?
    * f5 -> ")"
    */
   public R visit(MessageSend n, A argu) {
      R _ret=null;
      R type1 = n.f0.accept(this, argu); 
      if(((String)type1).equals("int[]"))
      {
         System.out.println("Symbol not found");
         System.exit(1);
      }
      n.f1.accept(this, argu);
      inmessage = true;
      n.f2.accept(this, argu);
      inmessage= false;
      n.f3.accept(this, argu);
      n.f4.accept(this, argu);
      n.f5.accept(this, argu);
       if(type1 == INT_R || type1 == BOOLEAN_R || type1 == INT_ARRAY_R||type1 == null){
         System.out.println("Type error");
         System.exit(0);
      }
      String temptype = (type1.toString()).trim();
      if(temptype.charAt(0)=='<'){
         currfuncallname = n.f2.f0.toString();
         if(currfuncallname!=null&&!currfuncallname.equals("apply")){
            System.out.println("Type error");
            System.exit(0);
         }else{
           if(currfunccalltypes!=null&&currfunccalltypes.size()==1&&currfunccalltypes.get(0)!=null&&(currfunccalltypes.get(0)).equals(curr_lambda_info.argtype)){
            _ret = (R) curr_lambda_info.rettype;
           }else{
               System.out.println("Type error");
            System.exit(0);
           }
         }
         currfuncallname = null;
         currfunccalltypes.clear();

      }else{
      currclasscall = type1.toString();
      if(!classesinfoMap.containsKey(currclasscall)){
         System.out.println("Symbol not found");
         System.exit(0);
      }else{
         currfuncallname = n.f2.f0.toString();
         _ret = check_func_call(currclasscall,currfuncallname,currfunccalltypes);
      }
      currclasscall = null;
      currfunccalltypes.clear();
   }
      return _ret;
   }

   /**
    * f0 -> Expression()
    * f1 -> ( ExpressionRest() )*
    */
   public R visit(ExpressionList n, A argu) {
      R _ret=null;
      R type1 = n.f0.accept(this, argu);
      if(type1 == null){
         System.out.println("Type error");
         System.exit(0);
      }
      currfunccalltypes.add(type1.toString());
      n.f1.accept(this, argu);
      return _ret;
   }

   /**
    * f0 -> ","
    * f1 -> Expression()
    */
   public R visit(ExpressionRest n, A argu) {
      R _ret=null;
      n.f0.accept(this, argu);
      R type1 =n.f1.accept(this, argu);
      if(type1 == null){
         System.out.println("Type error");
         System.exit(0);
      }
      currfunccalltypes.add(type1.toString());
      return _ret;
   }

   /**
    * f0 -> IntegerLiteral()
    *       | TrueLiteral()
    *       | FalseLiteral()
    *       | Identifier()
    *       | ThisExpression()
    *       | ArrayAllocationExpression()
    *       | AllocationExpression()
    *       | NotExpression()
    *       | BracketExpression()
    */
   public R visit(PrimaryExpression n, A argu) {
       return n.f0.accept(this, argu);
   }

   /**
    * f0 -> <INTEGER_LITERAL>
    */
   public R visit(IntegerLiteral n, A argu) {
      R _ret=null;
      n.f0.accept(this, argu);
      _ret = INT_R;
      return _ret;
   }

   /**
    * f0 -> "true"
    */
   public R visit(TrueLiteral n, A argu) {
      R _ret=null;
      n.f0.accept(this, argu);
      _ret = BOOLEAN_R;
      return _ret;
   }

   /**
    * f0 -> "false"
    */
   public R visit(FalseLiteral n, A argu) {
      R _ret=null;
      n.f0.accept(this, argu);
      _ret = BOOLEAN_R;
      return _ret;
   }

   /**
    * f0 -> <IDENTIFIER>
    */
   public R visit(Identifier n, A argu) {
      R _ret=null;
      n.f0.accept(this, argu);
     if(!inmessage&&!in_lambda_argument&&!in_lambda_info){
      if(!in_lambda_expression){
      _ret = check_declaration_error(n.f0.toString(),currclassinfo,currfuninfo);
      }else{
      String curr_var_name = n.f0.toString();
      String curr_lamargtype = new String();
      if(currfuninfo.func_lambdavarinfo.containsKey(curr_lambda_name)){
          NewLambdaType n1 = currfuninfo.func_lambdavarinfo.get(curr_lambda_name);
          curr_lamargtype = n1.argtype;
      }
      if(currclassinfo.class_lambdavarinfo.containsKey(curr_lambda_name)){
         NewLambdaType n1 = currclassinfo.class_lambdavarinfo.get(curr_lambda_name);
         curr_lamargtype = n1.argtype;
      }

      if(curr_var_name.equals(extra_arg)){
         
        _ret = (R)curr_lamargtype;
      }else{
      _ret = check_declaration_error(n.f0.toString(), currclassinfo, currfuninfo);
      }
   }
   String temptype = _ret.toString();
      if(temptype.charAt(0)=='<'){
         curr_lambda_name = n.f0.toString();
          if(currclassinfo.class_funcinfo.get(currfuninfo.name).func_lambdavarinfo.containsKey(curr_lambda_name)){
         curr_lambda_info= currclassinfo.class_funcinfo.get(currfuninfo.name).func_lambdavarinfo.get(curr_lambda_name);
       }else{
         curr_lambda_info = currclassinfo.class_lambdavarinfo.get(curr_lambda_name);
       }
      }
   
     }
      
      return _ret;
   }

   /**
    * f0 -> "this"
    */
   public R visit(ThisExpression n, A argu) {
      R _ret=null;
      n.f0.accept(this, argu);
      _ret = (R) currclass;
      return _ret;
   }

   /**
    * f0 -> "new"
    * f1 -> "int"
    * f2 -> "["
    * f3 -> Expression()
    * f4 -> "]"
    */
   public R visit(ArrayAllocationExpression n, A argu) {
      R _ret=null;
      n.f0.accept(this, argu);
      n.f1.accept(this, argu);
      n.f2.accept(this, argu);
      R type1 = n.f3.accept(this, argu);
      if(!type1.equals(INT_R)){
         System.out.println("Type error");
         System.exit(0);
      }else{
         _ret = INT_ARRAY_R;
      }
      n.f4.accept(this, argu);
      return _ret;
   }

   /**
    * f0 -> "new"
    * f1 -> Identifier()
    * f2 -> "("
    * f3 -> ")"
    */
   public R visit(AllocationExpression n, A argu) {
      R _ret=null;
      n.f0.accept(this, argu);
      R classname = n.f1.accept(this, argu);
      if(!classesinfoMap.containsKey(classname)){
         System.out.println("Symbol not found");
         System.exit(0);
      }else{
         _ret = (R) classname;
      }
      n.f2.accept(this, argu);
      n.f3.accept(this, argu);
      return _ret;
   }

   /**
    * f0 -> "!"
    * f1 -> Expression()
    */
   public R visit(NotExpression n, A argu) {
      R _ret=null;
      n.f0.accept(this, argu);
      R type1 = n.f1.accept(this, argu);
      if(!type1.equals(BOOLEAN_R)){
         System.out.println("Type error");
         System.exit(0);
      }else{
         _ret = BOOLEAN_R; 
      }
      return _ret;
   }

   /**
    * f0 -> "("
    * f1 -> Expression()
    * f2 -> ")"
    */
   public R visit(BracketExpression n, A argu) {
      R _ret=null;
      n.f0.accept(this, argu);
      R type1 =  n.f1.accept(this, argu);
      _ret = type1;
      n.f2.accept(this, argu);
      return _ret;
   }

}
