//
// Generated by JTB 1.3.2
//

package visitor;
import syntaxtree.*;
import java.util.*;

/**
 * Provides default methods which visit each node in the tree in depth-first
 * order.  Your visitors may extend this class.
 */
public class GJNoArguDepthFirst<R> implements GJNoArguVisitor<R> {
   String fp_ra_updates_main = "move $fp, $sp \n" +
                          "sw $ra, -4($fp)\n";
   String fp_ra_updates_non_main = "sw $fp, -8($sp)\n" + fp_ra_updates_main;
   String currlabelname = new String();
   int simpleexprtype = 0;   //0: default 1 : Integerliteral 2:  label 3: register
   int exprtype = 0 ; //0: default 1 : hallocate 2 : binop 3: simpleexp
   String extraregister = new String();
   boolean inmove = false;
   String operator = new String();
   String usesimpleexpr = new String();
   int currargcnt = 0;
   int spilledargno = 0;
   int maxargcalls =0;
   boolean indeepexpr = false;

   //
   // Auto class visitors--probably don't need to be overridden.
   //
   public R visit(NodeList n) {
      R _ret=null;
      int _count=0;
      for ( Enumeration<Node> e = n.elements(); e.hasMoreElements(); ) {
         e.nextElement().accept(this);
         _count++;
      }
      return _ret;
   }

   public R visit(NodeListOptional n) {
      if ( n.present() ) {
         R _ret=null;
         int _count=0;
         for ( Enumeration<Node> e = n.elements(); e.hasMoreElements(); ) {
            e.nextElement().accept(this);
            _count++;
         }
         return _ret;
      }
      else
         return null;
   }

   public R visit(NodeOptional n) {
      if ( n.present() )
         return n.node.accept(this);
      else
         return null;
   }

   public R visit(NodeSequence n) {
      R _ret=null;
      int _count=0;
      for ( Enumeration<Node> e = n.elements(); e.hasMoreElements(); ) {
         e.nextElement().accept(this);
         _count++;
      }
      return _ret;
   }

   public R visit(NodeToken n) { return null; }

   //
   // User-generated visitor methods below
   //

   /**
    * f0 -> "MAIN"
    * f1 -> "["
    * f2 -> IntegerLiteral()
    * f3 -> "]"
    * f4 -> "["
    * f5 -> IntegerLiteral()
    * f6 -> "]"
    * f7 -> "["
    * f8 -> IntegerLiteral()
    * f9 -> "]"
    * f10 -> StmtList()
    * f11 -> "END"
    * f12 -> ( SpillInfo() )?
    * f13 -> ( Procedure() )*
    * f14 -> <EOF>
    */
   public R visit(Goal n) {
      R _ret=null;
      n.f0.accept(this);
      n.f1.accept(this);
      currargcnt = Integer.valueOf(n.f2.accept(this).toString());
      n.f3.accept(this);
      n.f4.accept(this);
      int initialstacksize = Integer.valueOf(n.f5.accept(this).toString());
      
      n.f6.accept(this);
      n.f7.accept(this);
      maxargcalls = Integer.valueOf(n.f8.accept(this).toString());
      n.f9.accept(this);
      int  stacksize = (initialstacksize+Integer.max(maxargcalls-4,0)+1)*4;
      String stacksizestring = Integer.toString(stacksize);
      R stmts = n.f10.accept(this);
      n.f11.accept(this);
      currargcnt = 0;
      maxargcalls=0;
      n.f12.accept(this);
      String procedure = new String();
      // n.f13.accept(this);
      for ( Enumeration<Node> e = n.f13.elements(); e.hasMoreElements(); ) {
         procedure+=(e.nextElement().accept(this)).toString();
         
      }
      n.f14.accept(this);
      String mainheader = ".text \n" +
                          ".globl main\n"+
                          "main: \n" +
                          fp_ra_updates_main;
                           

      String printsection = ".text \n " + 
                            ".globl _print \n " +
                            "_print: \n  " + 
                            "li $v0, 1 \n" +
                            "syscall\n" +
                            "la $a0, newl\n" +
                            "li $v0, 4\n" +
                            "syscall\n" +
                            "j $ra\n" ;
      String hallocsection = ".text \n " + 
                            ".globl _halloc \n " +
                            "_halloc: \n  " + 
                            "li $v0, 9 \n" +
                            "syscall\n"+
                            "j $ra\n";
      String dataalignment = ".data\n"+
                           ".align 0\n";
      String datasection = dataalignment+
                           "newl:  .asciiz \"\\n\"\n"+
                           dataalignment;
      String errorlabel = "str_er: .asciiz  \"ERROR: abnormal termination\\n\"\n";

      String finalcode = mainheader + "subu  $sp, $sp, " + stacksizestring + "\n" + 
                        stmts.toString() + "addu $sp, $sp, " + stacksizestring + "\n"+
                        "lw $ra, -4($fp)\n"+
                        "j $ra\n" + procedure + "\n\n" + hallocsection + "\n\n" + printsection + "\n\n " +datasection +"\n\n"+ errorlabel;
      System.out.println(finalcode);

      return _ret;
   }

   /**
    * f0 -> ( ( Label() )? Stmt() )*
    */
   public R visit(StmtList n) {
      R _ret=null;
      n.f0.accept(this);
       String temp = new String();
      for ( Enumeration<Node> e = n.f0.elements(); e.hasMoreElements(); ) {
         NodeSequence seq = (NodeSequence)e.nextElement();
         for(Enumeration<Node> f = seq.elements(); f.hasMoreElements();){
            Node current = f.nextElement();
            if(current instanceof NodeOptional){
              NodeOptional nodeopt = (NodeOptional)current;
              if(nodeopt.present()){
               temp += (String)(nodeopt.node.accept(this)) + ":   ";
              }
         }else{
            String stmtsinfo = (String)(current.accept(this));
            temp += stmtsinfo  + "\n";
         }
         }
      }
      _ret = (R)temp;
      return _ret;
   }

   /**
    * f0 -> Label()
    * f1 -> "["
    * f2 -> IntegerLiteral()
    * f3 -> "]"
    * f4 -> "["
    * f5 -> IntegerLiteral()
    * f6 -> "]"
    * f7 -> "["
    * f8 -> IntegerLiteral()
    * f9 -> "]"
    * f10 -> StmtList()
    * f11 -> "END"
    * f12 -> ( SpillInfo() )?
    */
   public R visit(Procedure n) {
      R _ret=null;
      currlabelname = n.f0.accept(this).toString();
      n.f1.accept(this);
      R argcnt = n.f2.accept(this);
      currargcnt= Integer.valueOf(argcnt.toString());
      n.f3.accept(this);
      n.f4.accept(this);
      int initialstacksize = Integer.valueOf(n.f5.accept(this).toString());
      n.f6.accept(this);
      n.f7.accept(this);
      maxargcalls = Integer.valueOf(n.f8.accept(this).toString());
      n.f9.accept(this);
      int stacksize = (initialstacksize+Integer.max(0,maxargcalls-4)-Integer.max(0,currargcnt-4)+2)*4;
      String stacksizestring = Integer.toString(stacksize);
      R stmts = n.f10.accept(this);
      n.f11.accept(this);
      n.f12.accept(this);
      String procedurestring = ".text\n"+
                               ".globl  "+ currlabelname + "\n"+
                               currlabelname + ":\n"+
                               fp_ra_updates_non_main + 
                               "subu $sp, $sp, " + stacksizestring + "\n" +
                               stmts.toString() + 
                               "addu $sp, $sp, " + stacksizestring + "\n" +
                               "lw $ra, -4($sp)\n" +
                               "lw $fp, -8($sp)\n" +
                               "j $ra\n\n\n";
      _ret = (R)(procedurestring);
      currargcnt =0;
      maxargcalls =0;
      return _ret;
   }

   /**
    * f0 -> NoOpStmt()
    *       | ErrorStmt()
    *       | CJumpStmt()
    *       | JumpStmt()
    *       | HStoreStmt()
    *       | HLoadStmt()
    *       | MoveStmt()
    *       | PrintStmt()
    *       | ALoadStmt()
    *       | AStoreStmt()
    *       | PassArgStmt()
    *       | CallStmt()
    */
   public R visit(Stmt n) {
      R _ret=null;
      return n.f0.accept(this);
   }

   /**
    * f0 -> "NOOP"
    */
   public R visit(NoOpStmt n) {
      R _ret=null;
      n.f0.accept(this);
      _ret = (R)("nop");
      return _ret;
   }

   /**
    * f0 -> "ERROR"
    */
   public R visit(ErrorStmt n) {
      R _ret=null;
      n.f0.accept(this);
      _ret = (R)("li $v0, 4 \n " +
                 "la $a0, str_er\n" +
                 "syscall \n" +
                 "li $v0, 10\n" +
                 "syscall");
      return _ret;
   }

   /**
    * f0 -> "CJUMP"
    * f1 -> Reg()
    * f2 -> Label()
    */
   public R visit(CJumpStmt n) {
      R _ret=null;
      n.f0.accept(this);
      R register = n.f1.accept(this);
      R labelname = n.f2.accept(this);
      _ret = (R)("beqz  " + register.toString() + "  " + labelname );
      return _ret;
   }

   /**
    * f0 -> "JUMP"
    * f1 -> Label()
    */
   public R visit(JumpStmt n) {
      R _ret=null;
      n.f0.accept(this);
      R labelname = n.f1.accept(this);
      _ret = (R)("b  " + labelname);
      return _ret;
   }

   /**
    * f0 -> "HSTORE"
    * f1 -> Reg()
    * f2 -> IntegerLiteral()
    * f3 -> Reg()
    */
   public R visit(HStoreStmt n) {
      R _ret=null;
      n.f0.accept(this);
      String reg1 = n.f1.accept(this).toString();
      String offset = n.f2.accept(this).toString();
      String reg2 = n.f3.accept(this).toString();
      _ret = (R)("sw  " + reg2 + ",  " + offset + "(" + reg1 + ")");
      return _ret;
   }

   /**
    * f0 -> "HLOAD"
    * f1 -> Reg()
    * f2 -> Reg()
    * f3 -> IntegerLiteral()
    */
   public R visit(HLoadStmt n) {
      R _ret=null;
      n.f0.accept(this);
      String reg1 = n.f1.accept(this).toString();
      String reg2 = n.f2.accept(this).toString();
      String offset = n.f3.accept(this).toString();
      _ret = (R)("lw  " + reg1 + ",  " + offset + "(" + reg2 + ")");
      return _ret;
   }

   /**
    * f0 -> "MOVE"
    * f1 -> Reg()
    * f2 -> Exp()
    */
   public R visit(MoveStmt n) {
      inmove=true;
      R _ret=null;
      n.f0.accept(this);
      String reg1 = n.f1.accept(this).toString();
      n.f2.accept(this);
      String movestmt = new String();
      if(exprtype==1){
         if(simpleexprtype==1){
           movestmt+=("li $a0, "+ usesimpleexpr + "\n");
         }else{
            movestmt+=("move $a0, "+ usesimpleexpr+ "\n");
         }
         movestmt+=("jal _halloc\n");
         movestmt+=("move  "+ reg1 + ",  $v0" );
      }else{
         if(exprtype==2){
            switch(operator){
                 case "PLUS" : 
                 if(simpleexprtype==1){
                  movestmt+=("addi  " + reg1 + ",  "+ extraregister + ",  " + usesimpleexpr);
                 }else{
                  movestmt+=("add   " + reg1 + ",  "+ extraregister + ",  " + usesimpleexpr);
                 }
                 break;
                 case "MINUS" : 
                 if(simpleexprtype==1){
                  movestmt+=("subi  " + reg1 + ",  "+ extraregister + ",  " + usesimpleexpr);
                 }else{
                  movestmt+=("sub   " + reg1 + ",  "+ extraregister + ",  " + usesimpleexpr);
                 }
                 break;
                 case "TIMES" : 
                 if(simpleexprtype==1){
                  movestmt+=("li  $v1,  " + usesimpleexpr+ "\n");
                  movestmt+=("mul  " + reg1 + ",  "+ extraregister + ",  $v1");
                 }else{
                  movestmt+=("mul   " + reg1 + ",  "+ extraregister + ",  " + usesimpleexpr);
                 }
                 break;
                 case "DIV" : 
                 if(simpleexprtype==1){
                  movestmt+=("li  $v1,  " + usesimpleexpr+ "\n");
                  movestmt+=("div  " + extraregister + ",  $v1\n");
                  movestmt+=("mflo  " + reg1);
                 }else{
                  movestmt+=("div  " + extraregister + ",  " + usesimpleexpr + "\n");
                  movestmt+=("mflo  " + reg1);
                 }
                 break;
                 case "LE" : 
                 if(simpleexprtype==1){
                  String nextint = Integer.toString(Integer.valueOf(usesimpleexpr)+1);
                  movestmt+=("slti " + reg1 + ",  " + extraregister + ",  " + nextint);
                 }else{
                  movestmt+=("sle  " + reg1 + ",  " + extraregister + ",  " + usesimpleexpr);
                 }
                 break;
                 case "NE":
                 movestmt+=("sne   " + reg1 + ",  " + extraregister + ",  " + usesimpleexpr);
                 break;
                 default:
                 if(simpleexprtype==1){
                  movestmt+=("li  $v1,  " + usesimpleexpr+ "\n" );
                  movestmt+=("xor  " + reg1 + ",  " + extraregister + ",  v1\n");
                 }else{
                  movestmt+=("xor  " + reg1 + ",  " + extraregister + ",  " + usesimpleexpr + "\n");
                 }
                  movestmt+=("sltu " + reg1 + ",  $0,  " + reg1 );
                 break;
            }
          operator = "";
          extraregister = "";
         }else{
            if(simpleexprtype==1){
               movestmt+=("li  " + reg1 + ",  " + usesimpleexpr);
            }else{
               if(simpleexprtype==2){
                movestmt+=("la  " + reg1 + ",  "+ usesimpleexpr);
               }else{
                movestmt+=("move  " + reg1 + ",  " + usesimpleexpr);
               }
            }
         }
      }
      usesimpleexpr = "";
      simpleexprtype=0;
      exprtype = 0;
      inmove = false;
      indeepexpr = false;
      _ret = (R)movestmt;
      return _ret;
   }

   /**
    * f0 -> "PRINT"
    * f1 -> SimpleExp()
    */
   public R visit(PrintStmt n) {
      R _ret=null;
      n.f0.accept(this);
      R simpexpr = n.f1.accept(this);
      String printstatement = new String();
      if(simpleexprtype==1){
         printstatement+=("li $a0, " + simpexpr.toString() + "\n");
      }else{
         printstatement+=("move $a0, " + simpexpr.toString() + "\n" );
      }
      printstatement+=("jal _print");
      _ret = (R)(printstatement);
      simpleexprtype = 0;
      return _ret;
   }

   /**
    * f0 -> "ALOAD"
    * f1 -> Reg()
    * f2 -> SpilledArg()
    */
   public R visit(ALoadStmt n) {
      R _ret=null;
      n.f0.accept(this);
      String register = n.f1.accept(this).toString();
      n.f2.accept(this);
      String loadstmt = new String();
      if(spilledargno<Integer.max(0,currargcnt-4)){
         String offset = Integer.toString(spilledargno*4);
         loadstmt+=("lw  " + register + ",  " + offset + "($fp)");
      }else{
       String offset = Integer.toString((spilledargno+Integer.max(0,maxargcalls-4)-Integer.max(0,currargcnt-4))*4);
       loadstmt+=("lw  " + register + ",  " + offset + "($sp)");
      }
      spilledargno =0;
      _ret = (R)loadstmt;
      return _ret;
   }

   /**
    * f0 -> "ASTORE"
    * f1 -> SpilledArg()
    * f2 -> Reg()
    */
   public R visit(AStoreStmt n) {
      R _ret=null;
      n.f0.accept(this);
      n.f1.accept(this);
      String register = n.f2.accept(this).toString();
      String storestmt = new String();
      if(spilledargno<Integer.max(0,currargcnt-4)){
        String offset = Integer.toString(spilledargno*4);
         storestmt+=("sw  " + register + ",  " + offset + "($fp)");
      }else{
        String offset = Integer.toString((spilledargno+Integer.max(0,maxargcalls-4)-Integer.max(0,currargcnt-4))*4);
        storestmt+=("sw  " + register + ",  " + offset + "($sp)");
      }
      spilledargno = 0;
      _ret = (R)(storestmt);
      return _ret;
   }

   /**
    * f0 -> "PASSARG"
    * f1 -> IntegerLiteral()
    * f2 -> Reg()
    */
   public R visit(PassArgStmt n) {
      R _ret=null;
      n.f0.accept(this);
      String offset = n.f1.accept(this).toString();
      String originaloffset = Integer.toString((Integer.valueOf(offset)-1)*4);
      String register = n.f2.accept(this).toString();
      _ret = (R)("sw  " + register + ",  " + originaloffset + "($sp)");
      return _ret;
   }

   /**
    * f0 -> "CALL"
    * f1 -> SimpleExp()
    */
   public R visit(CallStmt n) {
      R _ret=null;
      n.f0.accept(this);
      String register = n.f1.accept(this).toString();
      _ret = (R)("jalr  " + register);
      return _ret;
   }

   /**
    * f0 -> HAllocate()
    *       | BinOp()
    *       | SimpleExp()
    */
   public R visit(Exp n) {
      R _ret=null;
      return n.f0.accept(this);
   }

   /**
    * f0 -> "HALLOCATE"
    * f1 -> SimpleExp()
    */
   public R visit(HAllocate n) {
      exprtype = 1;
      indeepexpr=true;
      R _ret=null;
      n.f0.accept(this);
      usesimpleexpr = n.f1.accept(this).toString();
      return _ret;
   }

   /**
    * f0 -> Operator()
    * f1 -> Reg()
    * f2 -> SimpleExp()
    */
   public R visit(BinOp n) {
      exprtype = 2;
      indeepexpr=true;
      R _ret=null;
      operator = n.f0.accept(this).toString();
      extraregister = n.f1.accept(this).toString();
      usesimpleexpr = n.f2.accept(this).toString();
      return _ret;
   }

   /**
    * f0 -> "LE"
    *       | "NE"
    *       | "PLUS"
    *       | "MINUS"
    *       | "TIMES"
    *       | "DIV"
    */
   public R visit(Operator n) {
      R _ret=null;
      NodeToken token = (NodeToken)n.f0.choice;
      String operator = token.tokenImage;
      _ret = (R)(operator);
      return _ret;
   }

   /**
    * f0 -> "SPILLEDARG"
    * f1 -> IntegerLiteral()
    */
   public R visit(SpilledArg n) {
      R _ret=null;
      n.f0.accept(this);
      spilledargno = Integer.valueOf(n.f1.accept(this).toString());
      return _ret;
   }

   /**
    * f0 -> Reg()
    *       | IntegerLiteral()
    *       | Label()
    */
   public R visit(SimpleExp n) {
      
      R _ret=null;
      _ret = (R)n.f0.accept(this).toString();
      if(inmove&&!indeepexpr){
         usesimpleexpr = _ret.toString();
      }
      return (R)(_ret);
   }

   /**
    * f0 -> "a0"
    *       | "a1"
    *       | "a2"
    *       | "a3"
    *       | "t0"
    *       | "t1"
    *       | "t2"
    *       | "t3"
    *       | "t4"
    *       | "t5"
    *       | "t6"
    *       | "t7"
    *       | "s0"
    *       | "s1"
    *       | "s2"
    *       | "s3"
    *       | "s4"
    *       | "s5"
    *       | "s6"
    *       | "s7"
    *       | "t8"
    *       | "t9"
    *       | "v0"
    *       | "v1"
    */
   public R visit(Reg n) {
      R _ret=null;
      simpleexprtype = 3;
      NodeToken token = (NodeToken)n.f0.choice;
      String register = token.tokenImage;
      _ret = (R)("$"+register);
      return _ret;
   }

   /**
    * f0 -> <INTEGER_LITERAL>
    */
   public R visit(IntegerLiteral n) {
      R _ret=null;
      simpleexprtype = 1;
      _ret = (R)n.f0.toString();
      return _ret;
   }

   /**
    * f0 -> <IDENTIFIER>
    */
   public R visit(Label n) {
      R _ret=null;
      simpleexprtype = 2;
      _ret = (R)n.f0.toString();
      return _ret;
   }

   /**
    * f0 -> "//"
    * f1 -> SpillStatus()
    */
   public R visit(SpillInfo n) {
      R _ret=null;
      n.f0.accept(this);
      n.f1.accept(this);
      return _ret;
   }

   /**
    * f0 -> <SPILLED>
    *       | <NOTSPILLED>
    */
   public R visit(SpillStatus n) {
      R _ret=null;
      n.f0.accept(this);
      return _ret;
   }

}
