//
// Generated by JTB 1.3.2
//

package visitor;
import syntaxtree.*;
import java.util.*;

/**
 * Provides default methods which visit each node in the tree in depth-first
 * order.  Your visitors may extend this class.
 */
public class GJNoArguDepthFirst<R> implements GJNoArguVisitor<R> {
   //
   // Auto class visitors--probably don't need to be overridden.
   //
   public int starttemp ;
   String temp_equations = new String();
   int  no_of_times = 0;
   boolean inexpression = false;
   boolean inmain = false;
   boolean normalliteral = false;
   boolean startinglabel = false;
   public GJNoArguDepthFirst(int maxtemp) {
      this.starttemp = maxtemp;
   }
   public R visit(NodeList n) {
      R _ret=null;
      int _count=0;
      for ( Enumeration<Node> e = n.elements(); e.hasMoreElements(); ) {
         e.nextElement().accept(this);
         _count++;
      }
      return _ret;
   }

   public R visit(NodeListOptional n) {
      if ( n.present() ) {
         R _ret=null;
         int _count=0;
         for ( Enumeration<Node> e = n.elements(); e.hasMoreElements(); ) {
            e.nextElement().accept(this);
            _count++;
         }
         return _ret;
      }
      else
         return null;
   }

   public R visit(NodeOptional n) {
      if ( n.present() )
         return n.node.accept(this);
      else
         return null;
   }

   public R visit(NodeSequence n) {
      R _ret=null;
      int _count=0;
      for ( Enumeration<Node> e = n.elements(); e.hasMoreElements(); ) {
         e.nextElement().accept(this);
         _count++;
      }
      return _ret;
   }

   public R visit(NodeToken n) { return null; }

   //
   // User-generated visitor methods below
   //

   /**
    * f0 -> "MAIN"
    * f1 -> StmtList()
    * f2 -> "END"
    * f3 -> ( Procedure() )*
    * f4 -> <EOF>
    */
   public R visit(Goal n) {
      R _ret=null;
      String temp = "MAIN\n";
      n.f0.accept(this);
      inmain = true;
      R stmts = n.f1.accept(this);
      inmain = false;
      temp +=(stmts.toString());
      // temp +=(temp_equations );
      temp_equations = "";
      n.f2.accept(this);
      temp  += "\nEND\n";
      // n.f3.accept(this);
      for ( Enumeration<Node> e = n.f3.elements(); e.hasMoreElements(); ) {
         temp += (String)(e.nextElement().accept(this));
      }
      n.f4.accept(this);
      System.out.println(temp);
      no_of_times = 0;
      return _ret;
   }

   /**
    * f0 -> ( ( Label() )? Stmt() )*
    */
   public R visit(StmtList n) {
      // System.out.println("Statement List");
      // return n.f0.accept(this);
      // return _ret;
      // System.out.println("StmtlistSTARTED");
      // String temp1 = new String(),temp2 = new String();
      String temp = new String();
      for ( Enumeration<Node> e = n.f0.elements(); e.hasMoreElements(); ) {
         NodeSequence seq = (NodeSequence)e.nextElement();
         for(Enumeration<Node> f = seq.elements(); f.hasMoreElements();){
            Node current = f.nextElement();
            if(current instanceof NodeOptional){
              NodeOptional nodeopt = (NodeOptional)current;
              if(nodeopt.present()){
               // temp1 += "LABSTART " + (String)(nodeopt.node.accept(this)) + " LABEND "; 
               startinglabel = true;
               temp += (String)(nodeopt.node.accept(this)) + "  ";
               startinglabel = false;
              }
         }else{
            // temp2 += "0000  " + (String)(current.accept(this)) + " 1111 ";
            String stmtsinfo = (String)(current.accept(this));
            if(!temp_equations.equals("")){
                temp+= temp_equations;
                temp_equations = "";
            }
            temp += stmtsinfo;
         }
         }
         // temp_equations += (temp1 + "  " + temp2);
      }
      // System.out.println(temp + " is the stmtlist");
      // System.out.println("StmtlistENDED");
      // System.out.println("pppppp\n\n" + temp_equations + "\n\nqqqqq\n\n");
      // System.out.println("Statement List ENDED");
      //  R _ret = null;
      // return (R)_ret;
      return (R)temp;
   }

   /**
    * f0 -> Label()
    * f1 -> "["
    * f2 -> IntegerLiteral()
    * f3 -> "]"
    * f4 -> StmtExp()
    */
   public R visit(Procedure n) {
      R _ret=null;
      // System.out.println("Procedure");
      String temp = new String();
      startinglabel = true;
      R labelstr = n.f0.accept(this);
      startinglabel = false;
      n.f1.accept(this);
      normalliteral = true;
      R intlit = n.f2.accept(this);
      normalliteral =false;
      temp += (labelstr.toString() + "  [" + intlit.toString() + " ] \nBEGIN\n" );
      n.f3.accept(this);
      // temp += "hi1";
      R stmts = n.f4.accept(this);
      // temp += (temp_equations +  "\nEND\n");
      temp += (temp_equations + stmts.toString() +  "\nEND\n");
      // temp += (stmts.toString() +  "\nEND\n");
      temp_equations = "";
      no_of_times = 0;
      _ret = (R)temp;
      return _ret;
   }

   /**
    * f0 -> NoOpStmt()
    *       | ErrorStmt()
    *       | CJumpStmt()
    *       | JumpStmt()
    *       | HStoreStmt()
    *       | HLoadStmt()
    *       | MoveStmt()
    *       | PrintStmt()
    */
   public R visit(Stmt n) {
      R _ret=null;
      return n.f0.accept(this);
      // return _ret;
   }

   /**
    * f0 -> "NOOP"
    */
   public R visit(NoOpStmt n) {
      R _ret=null;
      n.f0.accept(this);
      _ret = (R)("NOOP\n");
      return _ret;
   }

   /**
    * f0 -> "ERROR"
    */
   public R visit(ErrorStmt n) {
      R _ret=null;
      n.f0.accept(this);
      _ret = (R)("ERROR\n");
      return _ret;
   }

   /**
    * f0 -> "CJUMP"
    * f1 -> Exp()
    * f2 -> Label()
    */
   public R visit(CJumpStmt n) {
      R _ret=null;
      n.f0.accept(this);
      R expr = n.f1.accept(this);
      startinglabel = true;
      R labelstr = n.f2.accept(this);
      startinglabel = false;
      _ret = (R)("CJUMP  " + expr.toString() + " \n" +  labelstr.toString() + "\n");
      // temp_equations += ("CJUMP  " + expr.toString() + " " + labelstr.toString() + "\n");
      return _ret;
   }

   /**
    * f0 -> "JUMP"
    * f1 -> Label()
    */
   public R visit(JumpStmt n) {
      R _ret=null;
      n.f0.accept(this);
      startinglabel = true;
      R labelstr = n.f1.accept(this);
      startinglabel = false;
      _ret = (R)("JUMP  " + labelstr.toString() + "\n");
      // temp_equations += ("JUMP  " + labelstr.toString() + "\n");
      return _ret;
   }

   /**
    * f0 -> "HSTORE"
    * f1 -> Exp()
    * f2 -> IntegerLiteral()
    * f3 -> Exp()
    */
   public R visit(HStoreStmt n) {
      R _ret=null;
      n.f0.accept(this);
      R expr1 = n.f1.accept(this);
      normalliteral = true;
      R intlit = n.f2.accept(this);
      normalliteral = false;
      R expr2 = n.f3.accept(this);
      _ret = (R)("HSTORE  " + expr1.toString() + "   " +  intlit.toString() + "   " + expr2.toString() + "\n");
      // temp_equations += ("HSTORE  " + expr1.toString() + "   " +  intlit.toString() + "   " + expr2.toString() + "\n");
      return _ret;
   }

   /**
    * f0 -> "HLOAD"
    * f1 -> Temp()
    * f2 -> Exp()
    * f3 -> IntegerLiteral()
    */
   public R visit(HLoadStmt n) {
      R _ret=null;
      n.f0.accept(this);
      R tempstor = n.f1.accept(this);
      R expr = n.f2.accept(this);
      normalliteral = true;
      R intlit = n.f3.accept(this);
      normalliteral = false;
      _ret = (R)("HLOAD  " + tempstor.toString() + "   " + expr.toString() + " " + intlit.toString() + "\n");
      // temp_equations += ("HLOAD  " + tempstor.toString() + "   " + expr.toString() + " " + intlit.toString() + "\n");
      return _ret;
   }

   /**
    * f0 -> "MOVE"
    * f1 -> Temp()
    * f2 -> Exp()
    */
   public R visit(MoveStmt n) {
      R _ret=null;
      n.f0.accept(this);
      R tempstor = n.f1.accept(this);
      R expr = n.f2.accept(this);
      String presenttemp = Integer.toString(starttemp);
      starttemp++;
      _ret = (R)("MOVE  " + tempstor.toString() + "  " + expr.toString() + "\n");
      // temp_equations += ("MOVE  " + tempstor.toString() + "  " + expr.toString() + "\n");
      return _ret;
   }

   /**
    * f0 -> "PRINT"
    * f1 -> Exp()
    */
   public R visit(PrintStmt n) {
      R _ret=null;
      n.f0.accept(this);
      R expr = n.f1.accept(this);
      _ret = (R)("PRINT  " + expr.toString());
      // temp_equations += ("PRINT  " + expr.toString() + "\n");
      return _ret;
   }

   /**
    * f0 -> StmtExp()
    *       | Call()
    *       | HAllocate()
    *       | BinOp()
    *       | Temp()
    *       | IntegerLiteral()
    *       | Label()
    */
   public R visit(Exp n) {
      R _ret=null;
      return n.f0.accept(this);
   }

   /**
    * f0 -> "BEGIN"
    * f1 -> StmtList()
    * f2 -> "RETURN"
    * f3 -> Exp()
    * f4 -> "END"
    */
   public R visit(StmtExp n) {
      // System.out.println("Histart");
      R _ret=null;
      no_of_times++;
      n.f0.accept(this);
     R expr1 =  n.f1.accept(this);
      temp_equations += expr1.toString();
      n.f2.accept(this);
      R expr2 = n.f3.accept(this);
      n.f4.accept(this);
      String presenttemp = Integer.toString(starttemp);
      starttemp++;
      // System.out.println("Starttemp is " + presenttemp);
      temp_equations += ("MOVE TEMP " + presenttemp + " " + expr2.toString() + "\n");
      if(no_of_times ==1&&!inmain){
         _ret = (R)("RETURN TEMP " + presenttemp + "\n");
      }else{
         _ret = (R)("TEMP " + presenttemp + "\n");
      }
      no_of_times--;
      // System.out.println("Hiend");

      return _ret;
   }

   /**
    * f0 -> "CALL"
    * f1 -> Exp()
    * f2 -> "("
    * f3 -> ( Exp() )*
    * f4 -> ")"
    */
   public R visit(Call n) {
      R _ret=null;
      n.f0.accept(this);
      R expr1 = n.f1.accept(this);
      n.f2.accept(this);
      // n.f3.accept(this);
      inexpression = true;
      String temp = new String();
      for ( Enumeration<Node> e = n.f3.elements(); e.hasMoreElements(); ) {
         temp += ((e.nextElement().accept(this)).toString()+ "  ");
      }
      inexpression = false;
      String presenttemp = Integer.toString(starttemp);
      starttemp++;
      // System.out.println("Starttemp is " + presenttemp);
      temp_equations += ("MOVE  TEMP  " + presenttemp + " CALL  " + expr1.toString() + "  ( " + temp + " )\n " );
      n.f4.accept(this);
      _ret = (R)("TEMP  " + presenttemp);
      return _ret;
   }

   /**
    * f0 -> "HALLOCATE"
    * f1 -> Exp()
    */
   public R visit(HAllocate n) {
      R _ret=null;
      String prestemp = Integer.toString(starttemp);
      starttemp++;
      // System.out.println("Starttemp is " + prestemp);
      n.f0.accept(this);
      R expr = n.f1.accept(this);
      temp_equations += ("MOVE  TEMP  " + prestemp + "  HALLOCATE  "  + expr.toString() + "\n" );
      _ret = (R)("TEMP " + prestemp + "\n");
      return _ret;
   }

   /**
    * f0 -> Operator()
    * f1 -> Exp()
    * f2 -> Exp()
    */
   public R visit(BinOp n) {
      R _ret=null;
      R oper  = n.f0.accept(this);
      R expr1 = n.f1.accept(this);
      R expr2 = n.f2.accept(this);
      String presenttemp = Integer.toString(starttemp);
      starttemp ++;
      // System.out.println("Starttemp is " + presenttemp);
      temp_equations += ("MOVE  TEMP  " + presenttemp +  "  " + oper.toString() + "  " + expr1.toString() + "  " + expr2.toString() + "\n");
      _ret = (R)("TEMP  " + presenttemp + "\n");
      return _ret;
   }

   /**
    * f0 -> "LE"
    *       | "NE"
    *       | "PLUS"
    *       | "MINUS"
    *       | "TIMES"
    *       | "DIV"
    */
   public R visit(Operator n) {
      R _ret=null;
      NodeToken token = (NodeToken)n.f0.choice;
      String operator = token.tokenImage;
      _ret = (R)(operator);
      return _ret;
   }

   /**
    * f0 -> "TEMP"
    * f1 -> IntegerLiteral()
    */
   public R visit(Temp n) {
      R _ret=null;
      n.f0.accept(this);
      normalliteral = true;
      R intlit = n.f1.accept(this);
      normalliteral = false;
      // String presenttemp = Integer.toString(starttemp);
      // starttemp ++;
      // temp_equations += ("MOVE  TEMP  " +presenttemp  + "  TEMP " + intlit.toString() + "\n");
      _ret = (R)("TEMP  " + intlit.toString() + "");
      return _ret;
   }

   /**
    * f0 -> <INTEGER_LITERAL>
    */
   public R visit(IntegerLiteral n) {
      R _ret=null;
      n.f0.accept(this);
      if(normalliteral){
      _ret = (R)n.f0.toString() ;
      }else{
      String presenttemp = Integer.toString(starttemp);
      starttemp ++;
      // System.out.println("Starttemp is " + presenttemp);
      temp_equations += ("MOVE TEMP " + presenttemp + " " + n.f0.toString() + "\n");
      _ret = (R)("TEMP " + presenttemp + "\n");
      }

      return _ret;
   }

   /**
    * f0 -> <IDENTIFIER>
    */
   public R visit(Label n) {
      R _ret=null;
      n.f0.accept(this);
      if(startinglabel){
      _ret = (R)(n.f0.toString() );
      }else{
         String presenttemp = Integer.toString(starttemp);
         starttemp ++;
      // System.out.println("Starttemp is " + presenttemp);
         temp_equations += ("MOVE TEMP " + presenttemp + " " + n.f0.toString() + "\n");
         _ret = (R)("TEMP " + presenttemp + "\n");
      }
      startinglabel = false;
      return _ret;
   }

}
