//
// Generated by JTB 1.3.2
//

package visitor;
import syntaxtree.*;
import java.util.*;

/**
 * Provides default methods which visit each node in the tree in depth-first
 * order.  Your visitors may extend this class.
 */
public class DepthFirstVisitor implements Visitor {

   public Map<String,Classinfo> classesmapinfo = new HashMap<String,Classinfo>();
   String currclassname = new String();
   String currmthdname = new String();
   boolean infunction = false;
   String currtype = new String();
   boolean intype = false;
   Classinfo currclassinfo = null;
   Functioninfo currfuncinfo = null;
   Varinfo currvarinfo = null;
   String currmthd_label = null;
   Classinfo extendedclassinfo = null;
   String extendedclassname = null;

 public void printclasses() {
    for (Map.Entry<String, Classinfo> entry : classesmapinfo.entrySet()) {
        Classinfo cls = entry.getValue();

        System.out.println("==================================================================");
        System.out.println("Class: " + cls.name + 
            (cls.parent != null ? "  (extends " + cls.parent + ")" : ""));
        System.out.println("------------------------------------------------------------------");
        System.out.printf("%-15s %-15s %-15s %-15s\n", "#Variables", "#Functions", "Parent", "Class Name");
        System.out.printf("%-15d %-15d %-15s %-15s\n", 
            cls.no_of_variables, cls.no_of_functions, 
            (cls.parent != null ? cls.parent : "None"), cls.name);
        System.out.println("==================================================================");

        // ---------- Class Variables ----------
        if (!cls.class_varinfo.isEmpty()) {
            System.out.println("\nClass Variables:");
            System.out.printf("    %-15s %-15s %-15s\n", "Type", "Name", "Offset");
            System.out.println("    ---------------------------------------------------");
            for (Varinfo v : cls.class_varinfo.values()) {
                Integer offset = cls.offset_map_var.get(v.name);
                System.out.printf("    %-15s %-15s %-15s\n", v.type, v.name,
                    (offset != null ? offset.toString() : "-"));
            }
        } else {
            System.out.println("\nClass Variables: None");
        }

        // ---------- Print Variable Offset Map ----------
        if (!cls.offset_map_var.isEmpty()) {
            System.out.println("\n  Offset Map (Variables):");
            System.out.printf("      %-15s %-15s\n", "Var Name", "Offset");
            for (Map.Entry<String, Integer> e : cls.offset_map_var.entrySet()) {
                System.out.printf("      %-15s %-15s\n", e.getKey(), e.getValue());
            }
        }

        // ---------- Class Functions ----------
        if (!cls.class_funcinfo.isEmpty()) {
            System.out.println("\nFunctions:");
            System.out.printf("    %-15s %-20s %-15s %-20s\n",
                "Return Type", "Function Name", "Offset", "Label");
            System.out.println("    -----------------------------------------------------------------------------");

            for (Functioninfo f : cls.class_funcinfo.values()) {
                Integer offset = cls.offset_map_func.get(f.name);
                System.out.printf("    %-15s %-20s %-15s %-20s\n",
                    f.rettype, f.name,
                    (offset != null ? offset.toString() : "-"),
                    (f.labelname != null && !f.labelname.isEmpty() ? f.labelname : "-"));

                // ----- Parameters -----
                if (!f.func_param.isEmpty()) {
                    System.out.println("        Parameters:");
                    System.out.printf("            %-15s %-15s\n", "Type", "Name");
                    for (Varinfo p : f.func_param) {
                        System.out.printf("            %-15s %-15s\n", p.type, p.name);
                    }
                } else {
                    System.out.println("        Parameters: None");
                }

                // ----- Local Variables -----
                if (!f.func_varinfo.isEmpty()) {
                    System.out.println("        Local Variables:");
                    System.out.printf("            %-15s %-15s\n", "Type", "Name");
                    for (Varinfo v : f.func_varinfo.values()) {
                        System.out.printf("            %-15s %-15s\n", v.type, v.name);
                    }
                } else {
                    System.out.println("        Local Variables: None");
                }

                // ----- Print Function Maps -----
                if (!f.param_no_map.isEmpty()) {
                    System.out.println("        param_no_map:");
                    System.out.printf("            %-15s %-15s\n", "Param Name", "Param No");
                    for (Map.Entry<String, Integer> e : f.param_no_map.entrySet()) {
                        System.out.printf("            %-15s %-15s\n", e.getKey(), e.getValue());
                    }
                }

                if (!f.var_temp_no_map.isEmpty()) {
                    System.out.println("        var_temp_no_map:");
                    System.out.printf("            %-15s %-15s\n", "Var Name", "Temp No");
                    for (Map.Entry<String, Integer> e : f.var_temp_no_map.entrySet()) {
                        System.out.printf("            %-15s %-15s\n", e.getKey(), e.getValue());
                    }
                }

                System.out.println();
            }
        } else {
            System.out.println("\nFunctions: None");
        }

        // ---------- Print Function Offset Map ----------
        if (!cls.offset_map_func.isEmpty()) {
            System.out.println("\n  Offset Map (Functions):");
            System.out.printf("      %-15s %-15s\n", "Func Name", "Offset");
            for (Map.Entry<String, Integer> e : cls.offset_map_func.entrySet()) {
                System.out.printf("      %-15s %-15s\n", e.getKey(), e.getValue());
            }
        }

        System.out.println("==================================================================\n");
    }
}




   //
   // Auto class visitors--probably don't need to be overridden.
   //
   public void visit(NodeList n) {
      for ( Enumeration<Node> e = n.elements(); e.hasMoreElements(); )
         e.nextElement().accept(this);
   }

   public void visit(NodeListOptional n) {
      if ( n.present() )
         for ( Enumeration<Node> e = n.elements(); e.hasMoreElements(); )
            e.nextElement().accept(this);
   }

   public void visit(NodeOptional n) {
      if ( n.present() )
         n.node.accept(this);
   }

   public void visit(NodeSequence n) {
      for ( Enumeration<Node> e = n.elements(); e.hasMoreElements(); )
         e.nextElement().accept(this);
   }

   public void visit(NodeToken n) { }

   //
   // User-generated visitor methods below
   //

   /**
    * f0 -> ( ImportFunction() )?
    * f1 -> MainClass()
    * f2 -> ( TypeDeclaration() )*
    * f3 -> <EOF>
    */
   public void visit(Goal n) {
      n.f0.accept(this);
      n.f1.accept(this);
      n.f2.accept(this);
      n.f3.accept(this);
   }

   /**
    * f0 -> "import"
    * f1 -> "java.util.function.Function"
    * f2 -> ";"
    */
   public void visit(ImportFunction n) {
      n.f0.accept(this);
      n.f1.accept(this);
      n.f2.accept(this);
   }

   /**
    * f0 -> "class"
    * f1 -> Identifier()
    * f2 -> "{"
    * f3 -> "public"
    * f4 -> "static"
    * f5 -> "void"
    * f6 -> "main"
    * f7 -> "("
    * f8 -> "String"
    * f9 -> "["
    * f10 -> "]"
    * f11 -> Identifier()
    * f12 -> ")"
    * f13 -> "{"
    * f14 -> PrintStatement()
    * f15 -> "}"
    * f16 -> "}"
    */
   public void visit(MainClass n) {
      n.f0.accept(this);
      n.f1.accept(this);
      n.f2.accept(this);
      n.f3.accept(this);
      n.f4.accept(this);
      n.f5.accept(this);
      n.f6.accept(this);
      n.f7.accept(this);
      n.f8.accept(this);
      n.f9.accept(this);
      n.f10.accept(this);
      n.f11.accept(this);
      n.f12.accept(this);
      n.f13.accept(this);
      n.f14.accept(this);
      n.f15.accept(this);
      n.f16.accept(this);
   }

   /**
    * f0 -> ClassDeclaration()
    *       | ClassExtendsDeclaration()
    */
   public void visit(TypeDeclaration n) {
      n.f0.accept(this);
   }

   /**
    * f0 -> "class"
    * f1 -> Identifier()
    * f2 -> "{"
    * f3 -> ( VarDeclaration() )*
    * f4 -> ( MethodDeclaration() )*
    * f5 -> "}"
    */
   public void visit(ClassDeclaration n) {
      n.f0.accept(this);
      n.f1.accept(this);
      currclassname = n.f1.f0.toString();
      currclassinfo = new Classinfo(currclassname);
      classesmapinfo.put(currclassname,currclassinfo);
      n.f2.accept(this);
      n.f3.accept(this);
      n.f4.accept(this);
      n.f5.accept(this);
      currclassname = null;
   }

   /**
    * f0 -> "class"
    * f1 -> Identifier()
    * f2 -> "extends"
    * f3 -> Identifier()
    * f4 -> "{"
    * f5 -> ( VarDeclaration() )*
    * f6 -> ( MethodDeclaration() )*
    * f7 -> "}"
    */
   public void visit(ClassExtendsDeclaration n) {
      n.f0.accept(this);
      n.f1.accept(this);
       currclassname = n.f1.f0.toString();
       extendedclassname = n.f3.f0.toString();
       extendedclassinfo = classesmapinfo.get(extendedclassname);
       currclassinfo = new Classinfo(extendedclassinfo);
       classesmapinfo.put(currclassname,currclassinfo);
      n.f2.accept(this);
      n.f3.accept(this);
      n.f4.accept(this);
      n.f5.accept(this);
      n.f6.accept(this);
      n.f7.accept(this);
      currclassname = null;
      extendedclassinfo = null;
      extendedclassname = null;
   }

   /**
    * f0 -> Type()
    * f1 -> Identifier()
    * f2 -> ";"
    */
   public void visit(VarDeclaration n) {
      intype = true;
      n.f0.accept(this);
      intype = false;
      n.f1.accept(this);
      currvarinfo = new Varinfo(currtype,n.f1.f0.toString());
      if(infunction){
        classesmapinfo.get(currclassname).class_funcinfo.get(currclassname + "_" +currmthdname).func_varinfo.put(currvarinfo.name,currvarinfo);
      }else{
         classesmapinfo.get(currclassname).class_varinfo.put(currvarinfo.name,currvarinfo);
         int present_varcount = classesmapinfo.get(currclassname).no_of_variables;
         classesmapinfo.get(currclassname).offset_map_var.put(currvarinfo.name,present_varcount*4);
         classesmapinfo.get(currclassname).no_of_variables++;
      }
      currvarinfo= null;
      n.f2.accept(this);
   }

   /**
    * f0 -> "public"
    * f1 -> Type()
    * f2 -> Identifier()
    * f3 -> "("
    * f4 -> ( FormalParameterList() )?
    * f5 -> ")"
    * f6 -> "{"
    * f7 -> ( VarDeclaration() )*
    * f8 -> ( Statement() )*
    * f9 -> "return"
    * f10 -> Expression()
    * f11 -> ";"
    * f12 -> "}"
    */
   public void visit(MethodDeclaration n) {
      infunction = true;
      n.f0.accept(this);
      intype = true;
      n.f1.accept(this);
      intype = false;
      n.f2.accept(this);
      currmthdname = n.f2.f0.toString();
      n.f3.accept(this);
      currmthd_label = currclassname + "_" + currmthdname;
      currfuncinfo = new Functioninfo(currtype,currmthdname,currmthd_label); 
      int present_func_count = classesmapinfo.get(currclassname).no_of_functions;
      classesmapinfo.get(currclassname).class_funcinfo.put(currfuncinfo.labelname,currfuncinfo);
      classesmapinfo.get(currclassname).offset_map_func.put(currmthd_label,present_func_count*4);
      classesmapinfo.get(currclassname).no_of_functions++;

      n.f4.accept(this);

      n.f5.accept(this);
      n.f6.accept(this);
      n.f7.accept(this);

      int present_temp_count = classesmapinfo.get(currclassname).class_funcinfo.get(currclassname+ "_" + currmthdname).param_no;
      Map<String,Varinfo>  temp_map = classesmapinfo.get(currclassname).class_funcinfo.get(currmthd_label).func_varinfo;
      for (Map.Entry<String, Varinfo> entry : temp_map.entrySet()) {
    String key = entry.getKey();
    classesmapinfo.get(currclassname).class_funcinfo.get(currmthd_label).var_temp_no_map.put(key,present_temp_count);
    present_temp_count++;    
} 
classesmapinfo.get(currclassname).class_funcinfo.get(currmthd_label).total_temp_count= present_temp_count;
      n.f8.accept(this);
      n.f9.accept(this);
      n.f10.accept(this);
      n.f11.accept(this);
      n.f12.accept(this);
      currtype = null;
      infunction = false;
      currmthdname = null;
      currfuncinfo= null;
      currmthd_label = null;
   }

   /**
    * f0 -> FormalParameter()
    * f1 -> ( FormalParameterRest() )*
    */
   public void visit(FormalParameterList n) {
      n.f0.accept(this);
      n.f1.accept(this);
   }

   /**
    * f0 -> Type()
    * f1 -> Identifier()
    */
   public void visit(FormalParameter n) {
      intype = true;
      n.f0.accept(this);
      intype = false;
      n.f1.accept(this);
      currvarinfo = new Varinfo(currtype,n.f1.f0.toString());
      classesmapinfo.get(currclassname).class_funcinfo.get(currclassname+ "_" +currmthdname).func_param.add(currvarinfo);
      classesmapinfo.get(currclassname).class_funcinfo.get(currclassname + "_" +currmthdname).func_paramname.add(currvarinfo.name);
      classesmapinfo.get(currclassname).class_funcinfo.get(currclassname + "_" + currmthdname).func_paramtype.add(currvarinfo.type);
      int present_param_count=classesmapinfo.get(currclassname).class_funcinfo.get(currclassname + "_" + currmthdname).param_no;
      classesmapinfo.get(currclassname).class_funcinfo.get(currclassname + "_" + currmthdname).param_no_map.put(currvarinfo.name,present_param_count);
      classesmapinfo.get(currclassname).class_funcinfo.get(currclassname + "_" + currmthdname).param_no++;
      currvarinfo = null;


      currtype = null;
   }

   /**
    * f0 -> ","
    * f1 -> FormalParameter()
    */
   public void visit(FormalParameterRest n) {
      n.f0.accept(this);
      n.f1.accept(this);
   }

   /**
    * f0 -> ArrayType()
    *       | BooleanType()
    *       | IntegerType()
    *       | Identifier()
    *       | LambdaType()
    */
   public void visit(Type n) {
      n.f0.accept(this);
   }

   /**
    * f0 -> "int"
    * f1 -> "["
    * f2 -> "]"
    */
   public void visit(ArrayType n) {
      n.f0.accept(this);
      n.f1.accept(this);
      n.f2.accept(this);
      currtype = "int[]";
   }

   /**
    * f0 -> "boolean"
    */
   public void visit(BooleanType n) {
      currtype = "boolean";
      n.f0.accept(this);
   }

   /**
    * f0 -> "int"
    */
   public void visit(IntegerType n) {
      currtype = "int";
      n.f0.accept(this);
   }

   /**
    * f0 -> "Function"
    * f1 -> "<"
    * f2 -> Identifier()
    * f3 -> ","
    * f4 -> Identifier()
    * f5 -> ">"
    */
   public void visit(LambdaType n) {
      n.f0.accept(this);
      n.f1.accept(this);
      n.f2.accept(this);
      n.f3.accept(this);
      n.f4.accept(this);
      n.f5.accept(this);
   }

   /**
    * f0 -> Block()
    *       | AssignmentStatement()
    *       | ArrayAssignmentStatement()
    *       | IfStatement()
    *       | WhileStatement()
    *       | PrintStatement()
    */
   public void visit(Statement n) {
      n.f0.accept(this);
   }

   /**
    * f0 -> "{"
    * f1 -> ( Statement() )*
    * f2 -> "}"
    */
   public void visit(Block n) {
      n.f0.accept(this);
      n.f1.accept(this);
      n.f2.accept(this);
   }

   /**
    * f0 -> Identifier()
    * f1 -> "="
    * f2 -> Expression()
    * f3 -> ";"
    */
   public void visit(AssignmentStatement n) {
      n.f0.accept(this);
      n.f1.accept(this);
      n.f2.accept(this);
      n.f3.accept(this);
   }

   /**
    * f0 -> Identifier()
    * f1 -> "["
    * f2 -> Expression()
    * f3 -> "]"
    * f4 -> "="
    * f5 -> Expression()
    * f6 -> ";"
    */
   public void visit(ArrayAssignmentStatement n) {
      n.f0.accept(this);
      n.f1.accept(this);
      n.f2.accept(this);
      n.f3.accept(this);
      n.f4.accept(this);
      n.f5.accept(this);
      n.f6.accept(this);
   }

   /**
    * f0 -> IfthenElseStatement()
    *       | IfthenStatement()
    */
   public void visit(IfStatement n) {
      n.f0.accept(this);
   }

   /**
    * f0 -> "if"
    * f1 -> "("
    * f2 -> Expression()
    * f3 -> ")"
    * f4 -> Statement()
    */
   public void visit(IfthenStatement n) {
      n.f0.accept(this);
      n.f1.accept(this);
      n.f2.accept(this);
      n.f3.accept(this);
      n.f4.accept(this);
   }

   /**
    * f0 -> "if"
    * f1 -> "("
    * f2 -> Expression()
    * f3 -> ")"
    * f4 -> Statement()
    * f5 -> "else"
    * f6 -> Statement()
    */
   public void visit(IfthenElseStatement n) {
      n.f0.accept(this);
      n.f1.accept(this);
      n.f2.accept(this);
      n.f3.accept(this);
      n.f4.accept(this);
      n.f5.accept(this);
      n.f6.accept(this);
   }

   /**
    * f0 -> "while"
    * f1 -> "("
    * f2 -> Expression()
    * f3 -> ")"
    * f4 -> Statement()
    */
   public void visit(WhileStatement n) {
      n.f0.accept(this);
      n.f1.accept(this);
      n.f2.accept(this);
      n.f3.accept(this);
      n.f4.accept(this);
   }

   /**
    * f0 -> "System.out.println"
    * f1 -> "("
    * f2 -> Expression()
    * f3 -> ")"
    * f4 -> ";"
    */
   public void visit(PrintStatement n) {
      n.f0.accept(this);
      n.f1.accept(this);
      n.f2.accept(this);
      n.f3.accept(this);
      n.f4.accept(this);
   }

   /**
    * f0 -> OrExpression()
    *       | AndExpression()
    *       | CompareExpression()
    *       | neqExpression()
    *       | AddExpression()
    *       | MinusExpression()
    *       | TimesExpression()
    *       | DivExpression()
    *       | ArrayLookup()
    *       | ArrayLength()
    *       | MessageSend()
    *       | LambdaExpression()
    *       | PrimaryExpression()
    */
   public void visit(Expression n) {
      n.f0.accept(this);
   }

   /**
    * f0 -> "("
    * f1 -> Identifier()
    * f2 -> ")"
    * f3 -> "->"
    * f4 -> Expression()
    */
   public void visit(LambdaExpression n) {
      n.f0.accept(this);
      n.f1.accept(this);
      n.f2.accept(this);
      n.f3.accept(this);
      n.f4.accept(this);
   }

   /**
    * f0 -> PrimaryExpression()
    * f1 -> "&&"
    * f2 -> PrimaryExpression()
    */
   public void visit(AndExpression n) {
      n.f0.accept(this);
      n.f1.accept(this);
      n.f2.accept(this);
   }

   /**
    * f0 -> PrimaryExpression()
    * f1 -> "||"
    * f2 -> PrimaryExpression()
    */
   public void visit(OrExpression n) {
      n.f0.accept(this);
      n.f1.accept(this);
      n.f2.accept(this);
   }

   /**
    * f0 -> PrimaryExpression()
    * f1 -> "<="
    * f2 -> PrimaryExpression()
    */
   public void visit(CompareExpression n) {
      n.f0.accept(this);
      n.f1.accept(this);
      n.f2.accept(this);
   }

   /**
    * f0 -> PrimaryExpression()
    * f1 -> "!="
    * f2 -> PrimaryExpression()
    */
   public void visit(neqExpression n) {
      n.f0.accept(this);
      n.f1.accept(this);
      n.f2.accept(this);
   }

   /**
    * f0 -> PrimaryExpression()
    * f1 -> "+"
    * f2 -> PrimaryExpression()
    */
   public void visit(AddExpression n) {
      n.f0.accept(this);
      n.f1.accept(this);
      n.f2.accept(this);
   }

   /**
    * f0 -> PrimaryExpression()
    * f1 -> "-"
    * f2 -> PrimaryExpression()
    */
   public void visit(MinusExpression n) {
      n.f0.accept(this);
      n.f1.accept(this);
      n.f2.accept(this);
   }

   /**
    * f0 -> PrimaryExpression()
    * f1 -> "*"
    * f2 -> PrimaryExpression()
    */
   public void visit(TimesExpression n) {
      n.f0.accept(this);
      n.f1.accept(this);
      n.f2.accept(this);
   }

   /**
    * f0 -> PrimaryExpression()
    * f1 -> "/"
    * f2 -> PrimaryExpression()
    */
   public void visit(DivExpression n) {
      n.f0.accept(this);
      n.f1.accept(this);
      n.f2.accept(this);
   }

   /**
    * f0 -> PrimaryExpression()
    * f1 -> "["
    * f2 -> PrimaryExpression()
    * f3 -> "]"
    */
   public void visit(ArrayLookup n) {
      n.f0.accept(this);
      n.f1.accept(this);
      n.f2.accept(this);
      n.f3.accept(this);
   }

   /**
    * f0 -> PrimaryExpression()
    * f1 -> "."
    * f2 -> "length"
    */
   public void visit(ArrayLength n) {
      n.f0.accept(this);
      n.f1.accept(this);
      n.f2.accept(this);
   }

   /**
    * f0 -> PrimaryExpression()
    * f1 -> "."
    * f2 -> Identifier()
    * f3 -> "("
    * f4 -> ( ExpressionList() )?
    * f5 -> ")"
    */
   public void visit(MessageSend n) {
      n.f0.accept(this);
      n.f1.accept(this);
      n.f2.accept(this);
      n.f3.accept(this);
      n.f4.accept(this);
      n.f5.accept(this);
   }

   /**
    * f0 -> Expression()
    * f1 -> ( ExpressionRest() )*
    */
   public void visit(ExpressionList n) {
      n.f0.accept(this);
      n.f1.accept(this);
   }

   /**
    * f0 -> ","
    * f1 -> Expression()
    */
   public void visit(ExpressionRest n) {
      n.f0.accept(this);
      n.f1.accept(this);
   }

   /**
    * f0 -> IntegerLiteral()
    *       | TrueLiteral()
    *       | FalseLiteral()
    *       | Identifier()
    *       | ThisExpression()
    *       | ArrayAllocationExpression()
    *       | AllocationExpression()
    *       | NotExpression()
    *       | BracketExpression()
    */
   public void visit(PrimaryExpression n) {
      n.f0.accept(this);
   }

   /**
    * f0 -> <INTEGER_LITERAL>
    */
   public void visit(IntegerLiteral n) {
      n.f0.accept(this);
   }

   /**
    * f0 -> "true"
    */
   public void visit(TrueLiteral n) {
      n.f0.accept(this);
   }

   /**
    * f0 -> "false"
    */
   public void visit(FalseLiteral n) {
      n.f0.accept(this);
   }

   /**
    * f0 -> <IDENTIFIER>
    */
   public void visit(Identifier n) {
      if(intype){
         currtype = n.f0.toString();
      }
      n.f0.accept(this);
   }

   /**
    * f0 -> "this"
    */
   public void visit(ThisExpression n) {
      n.f0.accept(this);
   }

   /**
    * f0 -> "new"
    * f1 -> "int"
    * f2 -> "["
    * f3 -> Expression()
    * f4 -> "]"
    */
   public void visit(ArrayAllocationExpression n) {
      n.f0.accept(this);
      n.f1.accept(this);
      n.f2.accept(this);
      n.f3.accept(this);
      n.f4.accept(this);
   }

   /**
    * f0 -> "new"
    * f1 -> Identifier()
    * f2 -> "("
    * f3 -> ")"
    */
   public void visit(AllocationExpression n) {
      n.f0.accept(this);
      n.f1.accept(this);
      n.f2.accept(this);
      n.f3.accept(this);
   }

   /**
    * f0 -> "!"
    * f1 -> Expression()
    */
   public void visit(NotExpression n) {
      n.f0.accept(this);
      n.f1.accept(this);
   }

   /**
    * f0 -> "("
    * f1 -> Expression()
    * f2 -> ")"
    */
   public void visit(BracketExpression n) {
      n.f0.accept(this);
      n.f1.accept(this);
      n.f2.accept(this);
   }

}
