//
// Generated by JTB 1.3.2
//

package visitor;
import syntaxtree.*;
import java.util.*;

/**
 * Provides default methods which visit each node in the tree in depth-first
 * order.  Your visitors may extend this class.
 */
public class GJDepthFirst<R,A> implements GJVisitor<R,A> {

   Map<String,Classinfo> classesmapinfo = new HashMap<String,Classinfo>();
   public Map<String,Pair<Integer,String>> method_label_info = new HashMap<String,Pair<Integer,String>>();
   int labelno =0;
   int binary_flag = 0;
   boolean in_cond = false;
   String currclassname = new String();
   String currmthdname = new String();
   String currmthd_label = new String();
   boolean in_lhs_assign = false;
   boolean in_rhs_assign = false;
   boolean in_main = false;
   boolean in_class_decl = false;
   boolean class_var = false;
   boolean in_msg_class_call = false;
   boolean in_msg_call_fun = false;
   String currtype = new String();
   int global_main_temp_counter =1;
   boolean in_fun_type = false;
   boolean in_return_stmt = false;


   Map<Integer,String> temp_vars = new HashMap<Integer,String>();
   public GJDepthFirst(Map<String,Classinfo> classesmapinfo) {
      this.classesmapinfo = classesmapinfo;
   }
   //
   // Auto class visitors--probably don't need to be overridden.
   //
   public R visit(NodeList n, A argu) {
      R _ret=null;
      int _count=0;
      for ( Enumeration<Node> e = n.elements(); e.hasMoreElements(); ) {
         e.nextElement().accept(this,argu);
         _count++;
      }
      return _ret;
   }

   public R visit(NodeListOptional n, A argu) {
      if ( n.present() ) {
         R _ret=null;
         int _count=0;
         for ( Enumeration<Node> e = n.elements(); e.hasMoreElements(); ) {
            e.nextElement().accept(this,argu);
            _count++;
         }
         return _ret;
      }
      else
         return null;
   }

   public R visit(NodeOptional n, A argu) {
      if ( n.present() )
         return n.node.accept(this,argu);
      else
         return null;
   }

   public R visit(NodeSequence n, A argu) {
      R _ret=null;
      int _count=0;
      for ( Enumeration<Node> e = n.elements(); e.hasMoreElements(); ) {
         e.nextElement().accept(this,argu);
         _count++;
      }
      return _ret;
   }

   public R visit(NodeToken n, A argu) { return null; }

   //
   // User-generated visitor methods below
   //

   /**
    * f0 -> ( ImportFunction() )?
    * f1 -> MainClass()
    * f2 -> ( TypeDeclaration() )*
    * f3 -> <EOF>
    */
   public R visit(Goal n, A argu) {
      R _ret=null;
      n.f0.accept(this, argu);
      n.f1.accept(this, argu);
      n.f2.accept(this, argu);
      n.f3.accept(this, argu);
      return _ret;
   }

   /**
    * f0 -> "import"
    * f1 -> "java.util.function.Function"
    * f2 -> ";"
    */
   public R visit(ImportFunction n, A argu) {
      R _ret=null;
      n.f0.accept(this, argu);
      n.f1.accept(this, argu);
      n.f2.accept(this, argu);
      return _ret;
   }

   /**
    * f0 -> "class"
    * f1 -> Identifier()
    * f2 -> "{"
    * f3 -> "public"
    * f4 -> "static"
    * f5 -> "void"
    * f6 -> "main"
    * f7 -> "("
    * f8 -> "String"
    * f9 -> "["
    * f10 -> "]"
    * f11 -> Identifier()
    * f12 -> ")"
    * f13 -> "{"
    * f14 -> PrintStatement()
    * f15 -> "}"
    * f16 -> "}"
    */
   public R visit(MainClass n, A argu) {
      // System.out.println("cpdk");
      in_main = true;
      currclassname = null;
      R _ret=null;
      n.f0.accept(this, argu);
      n.f1.accept(this, argu);
      n.f2.accept(this, argu);
      n.f3.accept(this, argu);
      n.f4.accept(this, argu);
      n.f5.accept(this, argu);
      n.f6.accept(this, argu);
      n.f7.accept(this, argu);
      n.f8.accept(this, argu);
      n.f9.accept(this, argu);
      n.f10.accept(this, argu);

      // System.out.println("cpdk1");
      n.f11.accept(this, argu);
      // System.out.println("cpdk2");
      in_main = false;


      n.f12.accept(this, argu);
      n.f13.accept(this, argu);
      // System.out.println("cpdk3");

      R print_stmt =n.f14.accept(this, argu);
      // System.out.println("cpdk4");


      n.f15.accept(this, argu);
      n.f16.accept(this, argu);
      System.out.println("MAIN\n\n " + print_stmt.toString() + "\n\nEND\n\n\n" );
      return _ret;
   }

   /**
    * f0 -> ClassDeclaration()
    *       | ClassExtendsDeclaration()
    */
   public R visit(TypeDeclaration n, A argu) {
      R _ret=null;
      n.f0.accept(this, argu);
      return _ret;
   }

   /**
    * f0 -> "class"
    * f1 -> Identifier()
    * f2 -> "{"
    * f3 -> ( VarDeclaration() )*
    * f4 -> ( MethodDeclaration() )*
    * f5 -> "}"
    */
   public R visit(ClassDeclaration n, A argu) {
      R _ret=null;
      n.f0.accept(this, argu);
      in_class_decl = true;
      n.f1.accept(this, argu);
      in_class_decl = false;
      currclassname = n.f1.f0.toString();
      // System.out.println(currclassname);
      n.f2.accept(this, argu);
      n.f3.accept(this, argu);
      n.f4.accept(this, argu);
      n.f5.accept(this, argu);
      currclassname = null;
      return _ret;
   }

   /**
    * f0 -> "class"
    * f1 -> Identifier()
    * f2 -> "extends"
    * f3 -> Identifier()
    * f4 -> "{"
    * f5 -> ( VarDeclaration() )*
    * f6 -> ( MethodDeclaration() )*
    * f7 -> "}"
    */
   public R visit(ClassExtendsDeclaration n, A argu) {
      R _ret=null;
      n.f0.accept(this, argu);
      in_class_decl = true;
      n.f1.accept(this, argu);
      in_class_decl = false;
      
      currclassname = n.f1.f0.toString();
      n.f2.accept(this, argu);
      in_class_decl = true;
      n.f3.accept(this, argu);
      in_class_decl = false;
      n.f4.accept(this, argu);
      n.f5.accept(this, argu);
      n.f6.accept(this, argu);
      n.f7.accept(this, argu);
      currclassname = null;
      return _ret;
   }

   /**
    * f0 -> Type()
    * f1 -> Identifier()
    * f2 -> ";"
    */
   public R visit(VarDeclaration n, A argu) {
      R _ret=null;
      in_class_decl = true;

      n.f0.accept(this, argu);
      n.f1.accept(this, argu);
      n.f2.accept(this, argu);
      in_class_decl = false;

      return _ret;
   }

   /**
    * f0 -> "public"
    * f1 -> Type()
    * f2 -> Identifier()
    * f3 -> "("
    * f4 -> ( FormalParameterList() )?
    * f5 -> ")"
    * f6 -> "{"
    * f7 -> ( VarDeclaration() )*
    * f8 -> ( Statement() )*
    * f9 -> "return"
    * f10 -> Expression()
    * f11 -> ";"
    * f12 -> "}"
    */
   public R visit(MethodDeclaration n, A argu) {
      // System.out.println("hello");
      R _ret=null;
      n.f0.accept(this, argu);
      in_fun_type = true;
      n.f1.accept(this, argu);
      in_fun_type = false;
      in_class_decl = true;
      currmthdname = n.f2.accept(this, argu).toString();
      in_class_decl = false;
      currmthd_label = currclassname + "_" + currmthdname;
      // System.out.println(currmthd_label + "pppp");
      n.f3.accept(this, argu);
      in_fun_type = true;
      n.f4.accept(this, argu);
      n.f5.accept(this, argu);
      n.f6.accept(this, argu);
      n.f7.accept(this, argu);
      in_fun_type = false;
      // n.f8.accept(this, argu);
      String mult_stmt = new String();
      for ( Enumeration<Node> e = n.f8.elements(); e.hasMoreElements(); ) {
         //   if(e.nextElement().accept(this,argu)==null){
         //    System.out.println(currmthd_label);
         //    System.exit(0);
         //   }
            mult_stmt+=e.nextElement().accept(this,argu).toString();
         }
      n.f9.accept(this, argu);
      in_return_stmt = true;
      R expr = n.f10.accept(this, argu);
      in_return_stmt = false;
      n.f11.accept(this, argu);
      n.f12.accept(this, argu);
      String mthd_info = "\nBEGIN\n\n" + mult_stmt + "\nRETURN\n" + expr.toString() + "\n\nEND\n\n\n";
      int func_param_len = classesmapinfo.get(currclassname).class_funcinfo.get(currmthd_label).param_no;
      Pair<Integer,String> p = new Pair(func_param_len,mthd_info);
      method_label_info.put(currmthd_label,p);
      // System.out.println(p.second);
      currmthdname = null;
      return _ret;
   }

   /**
    * f0 -> FormalParameter()
    * f1 -> ( FormalParameterRest() )*
    */
   public R visit(FormalParameterList n, A argu) {
      R _ret=null;
      n.f0.accept(this, argu);
      n.f1.accept(this, argu);
      return _ret;
   }

   /**
    * f0 -> Type()
    * f1 -> Identifier()
    */
   public R visit(FormalParameter n, A argu) {
      in_class_decl = true;
      R _ret=null;
      n.f0.accept(this, argu);
      n.f1.accept(this, argu);
      in_class_decl = false;
      return _ret;
   }

   /**
    * f0 -> ","
    * f1 -> FormalParameter()
    */
   public R visit(FormalParameterRest n, A argu) {
      R _ret=null;
      n.f0.accept(this, argu);
      n.f1.accept(this, argu);
      return _ret;
   }

   /**
    * f0 -> ArrayType()
    *       | BooleanType()
    *       | IntegerType()
    *       | Identifier()
    *       | LambdaType()
    */
   public R visit(Type n, A argu) {
      R _ret=null;
      n.f0.accept(this, argu);
      return _ret;
   }

   /**
    * f0 -> "int"
    * f1 -> "["
    * f2 -> "]"
    */
   public R visit(ArrayType n, A argu) {
      R _ret=null;
      n.f0.accept(this, argu);
      n.f1.accept(this, argu);
      n.f2.accept(this, argu);
      return _ret;
   }

   /**
    * f0 -> "boolean"
    */
   public R visit(BooleanType n, A argu) {
      R _ret=null;
      n.f0.accept(this, argu);
      return _ret;
   }

   /**
    * f0 -> "int"
    */
   public R visit(IntegerType n, A argu) {
      R _ret=null;
      n.f0.accept(this, argu);
      return _ret;
   }

   /**
    * f0 -> "Function"
    * f1 -> "<"
    * f2 -> Identifier()
    * f3 -> ","
    * f4 -> Identifier()
    * f5 -> ">"
    */
   public R visit(LambdaType n, A argu) {
      R _ret=null;
      n.f0.accept(this, argu);
      n.f1.accept(this, argu);
      n.f2.accept(this, argu);
      n.f3.accept(this, argu);
      n.f4.accept(this, argu);
      n.f5.accept(this, argu);
      return _ret;
   }

   /**
    * f0 -> Block()
    *       | AssignmentStatement()
    *       | ArrayAssignmentStatement()
    *       | IfStatement()
    *       | WhileStatement()
    *       | PrintStatement()
    */
   public R visit(Statement n, A argu) {
      R _ret=null;
      return n.f0.accept(this, argu);
   }

   /**
    * f0 -> "{"
    * f1 -> ( Statement() )*
    * f2 -> "}"
    */
   public R visit(Block n, A argu) {
      R _ret=null;
      n.f0.accept(this, argu);
      String temp = new String();
      // n.f1.accept(this, argu);
      for ( Enumeration<Node> e = n.f1.elements(); e.hasMoreElements(); ) {
         temp += (e.nextElement().accept(this,argu)).toString();
      }
      n.f2.accept(this, argu);
      _ret = (R)temp;
      return _ret;
   }

   /**
    * f0 -> Identifier()
    * f1 -> "="
    * f2 -> Expression()
    * f3 -> ";"
    */
   public R visit(AssignmentStatement n, A argu) {
      // System.out.println("Hello");
      R _ret=null;
      in_lhs_assign = true;
      R id = n.f0.accept(this, argu);
      in_lhs_assign = false;
      n.f1.accept(this, argu);
      in_rhs_assign = true;
      R expr = n.f2.accept(this, argu);
      in_rhs_assign = false;
      n.f3.accept(this, argu);
      // System.out.println("sui");
      if(!class_var){
      _ret = (R)("MOVE  " + id.toString() + " \n\n  " + expr.toString() + "\n");
      }else{
         // if(id==null){
         //    System.out.println("pi");
         //    System.exit(0);
         // }
         // if(expr==null){
         //    System.out.println("pi2");
         //    System.exit(0);
         // }
         _ret = (R)(id.toString() + "   " + expr.toString() + "\n");
      }
      class_var = false;
      // System.out.println(_ret.toString());
      return _ret;
   }

   /**
    * f0 -> Identifier()
    * f1 -> "["
    * f2 -> Expression()
    * f3 -> "]"
    * f4 -> "="
    * f5 -> Expression()
    * f6 -> ";"
    */
   public R visit(ArrayAssignmentStatement n, A argu) {
      R _ret=null;
      R id = n.f0.accept(this, argu);
      n.f1.accept(this, argu);
      R expr1 = n.f2.accept(this, argu);
      n.f3.accept(this, argu);
      n.f4.accept(this, argu);
      R expr2 = n.f5.accept(this, argu);
      n.f6.accept(this, argu);
      int present_temp_count = classesmapinfo.get(currclassname).class_funcinfo.get(currmthd_label).total_temp_count;
      classesmapinfo.get(currclassname).class_funcinfo.get(currmthd_label).total_temp_count++;
      String pres_temp_String = Integer.toString(present_temp_count);
      _ret = (R)("MOVE TEMP " + pres_temp_String + "  " + id + "\n" +
                 "HSTORE  PLUS  TEMP "  + pres_temp_String + "   TIMES  PLUS  " + expr1 + "    1     4   0 " + expr2  +"\n\n");
      return _ret;
   }

   /**
    * f0 -> IfthenElseStatement()
    *       | IfthenStatement()
    */
   public R visit(IfStatement n, A argu) {
      R _ret=null;
      return n.f0.accept(this, argu);
   }

   /**
    * f0 -> "if"
    * f1 -> "("
    * f2 -> Expression()
    * f3 -> ")"
    * f4 -> Statement()
    */
   public R visit(IfthenStatement n, A argu) {
      R _ret=null;
      n.f0.accept(this, argu);
      n.f1.accept(this, argu);
      String if_expr1 = n.f2.accept(this, argu).toString();
      n.f3.accept(this, argu);
      // if(n.f4.accept(this,argu)==null){
      //    // System.out.println(if_expr1);
      //    System.exit(0);
      // }
      String if_stmt1 = n.f4.accept(this, argu).toString();
      String labelString1 = Integer.toString(labelno);
      labelno++;
      _ret = (R)("CJUMP   " + if_expr1 + "   L" + labelString1 + "\n" + if_stmt1 + "\n" + "L" + labelString1 + "     NOOP\n");
      return _ret;
   }

   /**
    * f0 -> "if"
    * f1 -> "("
    * f2 -> Expression()
    * f3 -> ")"
    * f4 -> Statement()
    * f5 -> "else"
    * f6 -> Statement()
    */
   public R visit(IfthenElseStatement n, A argu) {
      R _ret=null;
      n.f0.accept(this, argu);
      n.f1.accept(this, argu);
      String if_expr1 = n.f2.accept(this, argu).toString();
      n.f3.accept(this, argu);
      String if_stmt1 =n.f4.accept(this, argu).toString();
      n.f5.accept(this, argu);
      String if_stmt2 =n.f6.accept(this, argu).toString();
      String labelString1 = Integer.toString(labelno);
      labelno++;
      String labelString2 = Integer.toString(labelno);
      labelno++;
      _ret = (R)("CJUMP   " + if_expr1 + "   L" + labelString1 + "\n" + if_stmt1 + "\nJUMP   L" + labelString2 + "\nL"+ labelString1 + "  " + if_stmt2 + "\nL" + labelString2 + "   NOOP\n");
      return _ret;
   }

   /**
    * f0 -> "while"
    * f1 -> "("
    * f2 -> Expression()
    * f3 -> ")"
    * f4 -> Statement()
    */
   public R visit(WhileStatement n, A argu) {
      R _ret=null;
      n.f0.accept(this, argu);
      n.f1.accept(this, argu);
      String if_expr1 = n.f2.accept(this, argu).toString();
      n.f3.accept(this, argu);
      String while_stmt = n.f4.accept(this, argu).toString();
      String labelString1 = Integer.toString(labelno);
      labelno++;
      String labelString2 = Integer.toString(labelno);
      labelno++;
      _ret = (R)("L" + labelString1 + "   CJUMP " + if_expr1 + "  L" + labelString2 + "\n" + while_stmt + "\nJUMP    L" + labelString1 + "\nL" + labelString2 + "  NOOP\n" );
      return _ret;
   }

   /**
    * f0 -> "System.out.println"
    * f1 -> "("
    * f2 -> Expression()
    * f3 -> ")"
    * f4 -> ";"
    */
   public R visit(PrintStatement n, A argu) {
      R _ret=null;
      n.f0.accept(this, argu);
      n.f1.accept(this, argu);
      R expr = n.f2.accept(this, argu);
      n.f3.accept(this, argu);
      n.f4.accept(this, argu);
      _ret = (R)("PRINT "+ expr.toString() + "\n");
      return _ret;
   }

   /**
    * f0 -> OrExpression()
    *       | AndExpression()
    *       | CompareExpression()
    *       | neqExpression()
    *       | AddExpression()
    *       | MinusExpression()
    *       | TimesExpression()
    *       | DivExpression()
    *       | ArrayLookup()
    *       | ArrayLength()
    *       | MessageSend()
    *       | LambdaExpression()
    *       | PrimaryExpression()
    */
   public R visit(Expression n, A argu) {
      R _ret=null;
      return n.f0.accept(this, argu);
   }

   /**
    * f0 -> "("
    * f1 -> Identifier()
    * f2 -> ")"
    * f3 -> "->"
    * f4 -> Expression()
    */
   public R visit(LambdaExpression n, A argu) {
      R _ret=null;
      n.f0.accept(this, argu);
      n.f1.accept(this, argu);
      n.f2.accept(this, argu);
      n.f3.accept(this, argu);
      n.f4.accept(this, argu);
      return _ret;
   }

   /**
    * f0 -> PrimaryExpression()
    * f1 -> "&&"
    * f2 -> PrimaryExpression()
    */
   public R visit(AndExpression n, A argu) {
      R _ret=null;
      
      String expr1 = n.f0.accept(this, argu).toString();
      n.f1.accept(this, argu);
      String expr2 = n.f2.accept(this, argu).toString();
      String labelString1 = Integer.toString(labelno);
      labelno++;
      String labelString2 = Integer.toString(labelno);
      labelno++;
      int present_temp_count = classesmapinfo.get(currclassname).class_funcinfo.get(currmthd_label).total_temp_count;
      classesmapinfo.get(currclassname).class_funcinfo.get(currmthd_label).total_temp_count++;
      String pres_temp_String = Integer.toString(present_temp_count);
      _ret = (R)("\nBEGIN\n\n"+
                  "CJUMP   " + expr1 + "  L" + labelString1 + "\n"+
                  "CJUMP  " + expr2 + "  L" + labelString1 + "\n"+
                  "MOVE TEMP "+pres_temp_String + "  1\n"+
                  "JUMP  L" + labelString2 + "\n"+
                  "L" +  labelString1 + "   MOVE  TEMP " + pres_temp_String + " 0\n"+
                  "L" + labelString2 + "   NOOP RETURN  TEMP " + pres_temp_String + "\n"+
                  "\nEND\n"  );
      return _ret;
   }

   /**
    * f0 -> PrimaryExpression()
    * f1 -> "||"
    * f2 -> PrimaryExpression()
    */
   public R visit(OrExpression n, A argu) {
      R _ret=null;
      String expr1 = n.f0.accept(this, argu).toString();
      n.f1.accept(this, argu);
      String expr2 = n.f2.accept(this, argu).toString();
       String labelString1 = Integer.toString(labelno);
      labelno++;
      String labelString2 = Integer.toString(labelno);
      labelno++;
       String labelString3 = Integer.toString(labelno);
      labelno++;
      String labelString4 = Integer.toString(labelno);
      labelno++;
      int present_temp_count = classesmapinfo.get(currclassname).class_funcinfo.get(currmthd_label).total_temp_count;
      classesmapinfo.get(currclassname).class_funcinfo.get(currmthd_label).total_temp_count++;
      String pres_temp_String = Integer.toString(present_temp_count);
      _ret = (R)("\nBEGIN\n\nCJUMP   " + expr1 + "   L" + labelString1 + "\nL" + labelString3 + " MOVE TEMP " +  pres_temp_String + " 1\n"+
                 "JUMP  L" + labelString4 + "\n"+
                 "L" + labelString1 + "   CJUMP " + expr2 + "  L" + labelString2 + "\n" +
                 "JUMP L" + labelString3 + "\n" +
                 "L" + labelString2 + "   MOVE TEMP " + pres_temp_String + "  0\n"+
                 "L" + labelString4 + "   NOOP RETURN TEMP " + pres_temp_String + "\n\nEND\n");
      return _ret;
   }

   /**
    * f0 -> PrimaryExpression()
    * f1 -> "<="
    * f2 -> PrimaryExpression()
    */
   public R visit(CompareExpression n, A argu) {
      R _ret=null;
      R expr1 =n.f0.accept(this, argu);
      n.f1.accept(this, argu);
      R expr2 =n.f2.accept(this, argu);
      _ret = (R)("LE " + expr1.toString() + "   " + expr2.toString());
      return _ret;
   }

   /**
    * f0 -> PrimaryExpression()
    * f1 -> "!="
    * f2 -> PrimaryExpression()
    */
   public R visit(neqExpression n, A argu) {
      if(in_cond){
         binary_flag = 3;
      }
       R _ret=null;
      R expr1 =n.f0.accept(this, argu);
      n.f1.accept(this, argu);
      R expr2 =n.f2.accept(this, argu);
      _ret = (R)("NE " + expr1.toString() + "   " + expr2.toString());
      return _ret;
   }

   /**
    * f0 -> PrimaryExpression()
    * f1 -> "+"
    * f2 -> PrimaryExpression()
    */
   public R visit(AddExpression n, A argu) {
      R _ret=null;
      R expr1 = n.f0.accept(this, argu);
      n.f1.accept(this, argu);
      R expr2 = n.f2.accept(this, argu);
      _ret  = (R) ("PLUS   " + expr1.toString() + "   " + expr2.toString());
      return _ret;
   }

   /**
    * f0 -> PrimaryExpression()
    * f1 -> "-"
    * f2 -> PrimaryExpression()
    */
   public R visit(MinusExpression n, A argu) {
      R _ret=null;
      R expr1 = n.f0.accept(this, argu);
      n.f1.accept(this, argu);
      R expr2 = n.f2.accept(this, argu);
      _ret  = (R) ("MINUS  " + expr1.toString() + "   " + expr2.toString());
      return _ret;
   }

   /**
    * f0 -> PrimaryExpression()
    * f1 -> "*"
    * f2 -> PrimaryExpression()
    */
   public R visit(TimesExpression n, A argu) {
     R _ret=null;
      R expr1 = n.f0.accept(this, argu);
      n.f1.accept(this, argu);
      R expr2 = n.f2.accept(this, argu);
      _ret  = (R) ("TIMES  " + expr1.toString() + "   " + expr2.toString());
      return _ret;
   }

   /**
    * f0 -> PrimaryExpression()
    * f1 -> "/"
    * f2 -> PrimaryExpression()
    */
   public R visit(DivExpression n, A argu) {
      R _ret=null;
      R expr1 = n.f0.accept(this, argu);
      n.f1.accept(this, argu);
      R expr2 = n.f2.accept(this, argu);
      _ret  = (R) ("DIV  " + expr1.toString() + "   " + expr2.toString());
      return _ret;
   }

   /**
    * f0 -> PrimaryExpression()
    * f1 -> "["
    * f2 -> PrimaryExpression()
    * f3 -> "]"
    */
   public R visit(ArrayLookup n, A argu) {
      R _ret=null;
      R expr1 = n.f0.accept(this, argu);
      n.f1.accept(this, argu);
      R expr2 = n.f2.accept(this, argu);
      n.f3.accept(this, argu);
      int present_temp_count = classesmapinfo.get(currclassname).class_funcinfo.get(currmthd_label).total_temp_count;
      classesmapinfo.get(currclassname).class_funcinfo.get(currmthd_label).total_temp_count+=2;
      String pres_temp_String1 = Integer.toString(present_temp_count);
      String pres_temp_String2 = Integer.toString(present_temp_count+1);
      _ret = (R)("\nBEGIN\n\n" + 
                 "MOVE  TEMP  " +  pres_temp_String1 + " " + expr1 + "\n" +
                 "HLOAD  TEMP  " + pres_temp_String2 + "  PLUS  TEMP " + pres_temp_String1 + "   TIMES  PLUS  " + expr2 + "   1   4  0 \n"+
                 "RETURN TEMP " +pres_temp_String2 + "\n" +
                 "\nEND\n");
      return _ret;
   }

   /**
    * f0 -> PrimaryExpression()
    * f1 -> "."
    * f2 -> "length"
    */
   public R visit(ArrayLength n, A argu) {
      R _ret=null;
      R expr1 = n.f0.accept(this, argu);
      n.f1.accept(this, argu);
      n.f2.accept(this, argu);
      int present_temp_count = classesmapinfo.get(currclassname).class_funcinfo.get(currmthd_label).total_temp_count;
      classesmapinfo.get(currclassname).class_funcinfo.get(currmthd_label).total_temp_count+=2;
      String pres_temp_String1 = Integer.toString(present_temp_count);
      String pres_temp_String2 = Integer.toString(present_temp_count+1);
      _ret = (R)("\nBEGIN\n\n"+
                 "MOVE TEMP " + pres_temp_String1 + expr1 + "\n" +
                 "HLOAD  TEMP " + pres_temp_String2 + "  TEMP " + pres_temp_String1 + "   0  \n" +
                 "RETURN TEMP " + pres_temp_String2 + "\n" +
                 "\nEND\n");
      return _ret;
   }

   /**
    * f0 -> PrimaryExpression()
    * f1 -> "."
    * f2 -> Identifier()
    * f3 -> "("
    * f4 -> ( ExpressionList() )?
    * f5 -> ")"
    */
   public R visit(MessageSend n, A argu) {
      R _ret=null;
      in_msg_class_call = true;
      // if(n.f0.accept(this,argu)==null){
      //    System.out.println(currclassname + "wahh");
      //    System.exit(0);
      // }
      String id = n.f0.accept(this, argu).toString();
      // System.out.println(id + "  hello");
      in_msg_class_call = false;
      n.f1.accept(this, argu);
      in_msg_call_fun= true;
      String  currfuncallname = n.f2.accept(this, argu).toString();
      in_msg_call_fun = false;
      String curr_mthd_call_label = currtype + "_" + currfuncallname;
      // System.out.println(curr_mthd_call_label+ "   lii");
      n.f3.accept(this, argu);
      int present_temp_count = 1 ;
      if(currclassname ==null){
         present_temp_count = global_main_temp_counter;
         global_main_temp_counter+=3;
      }else{
         present_temp_count = classesmapinfo.get(currclassname).class_funcinfo.get(currmthd_label).total_temp_count;
      classesmapinfo.get(currclassname).class_funcinfo.get(currmthd_label).total_temp_count+=3;
      }
      String pres_temp_String1 = Integer.toString(present_temp_count);
      String pres_temp_String2 = Integer.toString(present_temp_count+1);
      String pres_temp_String3 = Integer.toString(present_temp_count+2);
      int fun_offset=0;
      String temp = currtype;
      String itr = currtype;
      // System.out.println(currtype+ "   inmsgtypea");
      Classinfo callingclassinfo = classesmapinfo.get(currtype);
      // if(callingclassinfo==null){
      //       System.out.println(currmthd_label + "  " + currtype + " " + curr_mthd_call_label);
      //       System.exit(0);
      //  }
      while(itr!=null){
           curr_mthd_call_label = itr + "_" + currfuncallname;
           if(callingclassinfo.class_funcinfo.containsKey(curr_mthd_call_label)){
            fun_offset = callingclassinfo.offset_map_func.get(curr_mthd_call_label);
            currtype = callingclassinfo.class_funcinfo.get(curr_mthd_call_label).rettype;
            break;
           }
           itr = classesmapinfo.get(itr).parent;
      }
      // if(currfuncallname.equals("GetLeft")||currfuncallname.equals("GetRight")){
      //    System.out.println("type : " + currtype);
      //    System.out.println("offset : " + fun_offset);
      // }
      String exprlist = new String();
      if(n.f4.present())exprlist = (String)n.f4.accept(this, argu);
      n.f5.accept(this, argu);
      String fun_offset_string = Integer.toString(fun_offset);
      _ret = (R)("\nCALL\n\nBEGIN\n\nMOVE TEMP " + pres_temp_String1 + "  " + id + "\n" +
                 "HLOAD  TEMP " +pres_temp_String2 + " TEMP " + pres_temp_String1 + " 0 \n" +
                 "HLOAD  TEMP " +pres_temp_String3 + " TEMP " + pres_temp_String2 + " " + fun_offset_string + "\n" +
                 "RETURN TEMP " +pres_temp_String3 + "\n"+
                 "\n\nEND\n" +
                 "(" + " TEMP " + pres_temp_String1 + " " + exprlist + ")\n");
      // System.out.println(currtype+ curr_mthd_call_label + "   inmsgtypeb");
      return _ret;
   }

   /**
    * f0 -> Expression()
    * f1 -> ( ExpressionRest() )*
    */
   public R visit(ExpressionList n, A argu) {
      R _ret=null;
      String expr1 = n.f0.accept(this, argu).toString();
      String expr2 = new String();
      for ( Enumeration<Node> e = n.f1.elements(); e.hasMoreElements(); ) {
         expr2 +=(String)e.nextElement().accept(this,argu);
      }
      _ret = (R)(expr1 + "   " );
      if(expr2!=null){
         _ret = (R)(_ret.toString() + expr2);
      }
      
      return _ret;
   }

   /**
    * f0 -> ","
    * f1 -> Expression()
    */
   public R visit(ExpressionRest n, A argu) {
      R _ret=null;
      n.f0.accept(this, argu);
      _ret = (R)(" " + n.f1.accept(this, argu).toString());
      return _ret;
   }

   /**
    * f0 -> IntegerLiteral()
    *       | TrueLiteral()
    *       | FalseLiteral()
    *       | Identifier()
    *       | ThisExpression()
    *       | ArrayAllocationExpression()
    *       | AllocationExpression()
    *       | NotExpression()
    *       | BracketExpression()
    */
   public R visit(PrimaryExpression n, A argu) {
      R _ret=null;
      return n.f0.accept(this, argu);
   }

   /**
    * f0 -> <INTEGER_LITERAL>
    */
   public R visit(IntegerLiteral n, A argu) {
      R _ret=null;
      n.f0.accept(this, argu);
      _ret = (R)(n.f0.toString());
      return _ret;
   }

   /**
    * f0 -> "true"
    */
   public R visit(TrueLiteral n, A argu) {
      R _ret=null;
      n.f0.accept(this, argu);
      _ret = (R)(Integer.toString(1));
      return _ret;
   }

   /**
    * f0 -> "false"
    */
   public R visit(FalseLiteral n, A argu) {
      R _ret=null;
      n.f0.accept(this, argu);
      _ret = (R)(Integer.toString(0));
      return _ret;
   }

   /**
    * f0 -> <IDENTIFIER>
    */
   public R visit(Identifier n, A argu) {
      R _ret=null;
      if(in_main||in_fun_type){
         return _ret;
      }
      n.f0.accept(this, argu);
      String temp = n.f0.toString();
      // System.out.println(temp);
      if(in_class_decl||in_msg_call_fun){
         return (R)temp;
      }
      if(in_msg_class_call){
      // System.out.println(currtype + "  A");
         Functioninfo currfuninfo = classesmapinfo.get(currclassname).class_funcinfo.get(currmthd_label);
         Classinfo currclassinfo = classesmapinfo.get(currclassname);
         if(currfuninfo.param_no_map.containsKey(temp)){
            // System.out.println("y1");
            int idx = currfuninfo.param_no_map.get(temp);
            // System.out.println(idx+ "pp");
            // for(int i =0 ;i< currfuninfo.func_paramname.size();i++){
            //    System.out.println(currfuninfo.func_paramname.elementAt(i));
            // }
            // for(int i =0 ;i< currfuninfo.func_paramtype.size();i++){
            //    System.out.println(currfuninfo.func_paramtype.elementAt(i));
            // }
            currtype = currfuninfo.func_paramtype.elementAt(idx-1);
         }else{
            if(currfuninfo.func_varinfo.containsKey(temp)){
            // System.out.println("y2");
               currtype = currfuninfo.func_varinfo.get(temp).type;
            }else{
            // System.out.println("y3");
               currtype = currclassinfo.class_varinfo.get(temp).type;
            }
         }
         // System.out.println(temp + "lm kmc");
      // System.out.println(currtype + "   B");

      }
      // if(!classesmapinfo.get(currclassname).class_funcinfo.containsKey(currmthd_label)){
         // System.out.println(currclassname+ " ooo " + currmthd_label);
         // System.exit(0);
      // }
      // if(!classesmapinfo.containsKey(currclassname)){
      //        System.out.println(currclassname+ " ooo ");
      //    System.exit(0);
      // }
      if(currclassname==null){
         return null;
      }
      Map<String,Integer> m = classesmapinfo.get(currclassname).class_funcinfo.get(currmthd_label).param_no_map;
      if(m.containsKey(temp)){
         int param_no = m.get(temp);
         _ret = (R)("TEMP  " + Integer.toString(param_no));
      }else{
          Map<String,Integer> m1 = classesmapinfo.get(currclassname).class_funcinfo.get(currmthd_label).var_temp_no_map;
          if(m1.containsKey(temp)){
            int param_no = m1.get(temp);
            _ret = (R)("TEMP  " + Integer.toString(param_no));
          }else{
            // if(!classesmapinfo.get(currclassname).offset_map_var.containsKey(temp)){
            //    System.out.println("seeeee " + currclassname + " " + currmthd_label + " " + temp );
            //    System.exit(0);
            // }
            int var_offset = classesmapinfo.get(currclassname).offset_map_var.get(temp);
            int present_temp_count = classesmapinfo.get(currclassname).class_funcinfo.get(currmthd_label).total_temp_count;
            if(in_lhs_assign){
               class_var = true;
               _ret = (R)("HSTORE  TEMP 0  " + Integer.toString(var_offset) + "  ");
            }else{
               classesmapinfo.get(currclassname).class_funcinfo.get(currmthd_label).total_temp_count++;
              _ret = (R)("\nBEGIN \n\nHLOAD TEMP " + Integer.toString(present_temp_count) + "  TEMP 0  " + Integer.toString(var_offset) + "\nRETURN   TEMP  " + Integer.toString(present_temp_count) +"  \n\nEND\n" );
            }
          }
      }
      return _ret;
   }

   /**
    * f0 -> "this"
    */
   public R visit(ThisExpression n, A argu) {
      R _ret=null;
      n.f0.accept(this, argu);
      if(in_msg_class_call){
         currtype = currclassname;
      }
      int present_temp_count = classesmapinfo.get(currclassname).class_funcinfo.get(currmthd_label).total_temp_count;
      classesmapinfo.get(currclassname).class_funcinfo.get(currmthd_label).total_temp_count++;
      String pres_temp_String1 = Integer.toString(present_temp_count);
      
      _ret = (R)(" TEMP 0 " );
      return _ret;
   }

   /**
    * f0 -> "new"
    * f1 -> "int"
    * f2 -> "["
    * f3 -> Expression()
    * f4 -> "]"
    */
   public R visit(ArrayAllocationExpression n, A argu) {
      R _ret=null;
      n.f0.accept(this, argu);
      n.f1.accept(this, argu);
      n.f2.accept(this, argu);
      R expr1 =  n.f3.accept(this, argu);
      int present_temp_count = classesmapinfo.get(currclassname).class_funcinfo.get(currmthd_label).total_temp_count;
      classesmapinfo.get(currclassname).class_funcinfo.get(currmthd_label).total_temp_count+=2;
      String pres_temp_String1 = Integer.toString(present_temp_count);
      String pres_temp_String2 = Integer.toString(present_temp_count+1);
      String labelString1 = Integer.toString(labelno);
      labelno++;
      String labelString2 = Integer.toString(labelno);
      labelno++;
      n.f4.accept(this, argu);
      _ret = (R) ("\nBEGIN\n\n" +
                  "MOVE    TEMP " + pres_temp_String1 + "   HALLOCATE  TIMES PLUS  " + expr1 + "   1   4 \n" + 
                  "MOVE    TEMP " + pres_temp_String2 + "   4 " +
                  "L" + labelString1 + "  CJUMP    LE  TEMP " + pres_temp_String2 + " MINUS  TIMES  PLUS  " + expr1 + "  1   4  1  L" + labelString2 + 
                  " HSTORE  PLUS  TEMP " + pres_temp_String1 + "   TEMP " + pres_temp_String2 + " 0   0\n" +
                  "MOVE    TEMP " + pres_temp_String2 + "   PLUS    TEMP " + pres_temp_String2 + "    4 " + 
                  "JUMP   L" + labelString1 + "\n" +
                  "L" + labelString2 + "  HSTORE  TEMP " + pres_temp_String1 + " 0   " + expr1 + "\n" +
                  "RETURN TEMP " + pres_temp_String1 + "\n" +
                  "\nEND\n");
      return _ret;
   }

   /**
    * f0 -> "new"
    * f1 -> Identifier()
    * f2 -> "("
    * f3 -> ")"
    */
   public R visit(AllocationExpression n, A argu) {
      R _ret=null;
      n.f0.accept(this, argu);
      in_class_decl = true;
      boolean temp_bool = in_msg_class_call;
      if(in_msg_class_call){
      in_msg_class_call = false;
      }
      R temp = n.f1.accept(this, argu);
      in_msg_class_call = temp_bool;
      in_class_decl = false;
      n.f2.accept(this, argu);
      String classname = temp.toString();
      int temp_count=0;
      // System.out.println(temp.toString()+"ppp");
      if(currclassname == null){
        temp_count = global_main_temp_counter;
      }else{
      // if(!classesmapinfo.containsKey(currclassname)){
      //    System.out.println(currclassname + "System print!");
      //    System.exit(0);
      // }
      temp_count = classesmapinfo.get(currclassname).class_funcinfo.get(currmthd_label).total_temp_count;
      }
      int fun_len = (classesmapinfo.get(classname).no_of_functions)*4;
      int var_len = (classesmapinfo.get(classname).no_of_variables)*4;
      n.f3.accept(this, argu);
      String newallocator = new String();
      if(in_rhs_assign||currclassname==null||in_return_stmt){
         if(currclassname!=null){
         classesmapinfo.get(currclassname).class_funcinfo.get(currmthd_label).total_temp_count+=2;
         }else{
            global_main_temp_counter+=2;
         }
            String temp1 = Integer.toString(temp_count),temp2 = Integer.toString(temp_count+1);
          newallocator = newallocator + "BEGIN  \n\nMOVE   TEMP  " + temp1 + "   HALLOCATE " + Integer.toString(fun_len) + "\nMOVE  TEMP " + temp2 + "  HALLOCATE  " + Integer.toString(var_len) + "\n";  
          Map<String,Integer> m = classesmapinfo.get(classname).offset_map_func;
          for(Map.Entry<String,Integer> entry:m.entrySet()){
            String fun_lab_name = entry.getKey(),fun_offset = Integer.toString(entry.getValue());
            newallocator+=("HSTORE  TEMP  " + temp1 + "  " + fun_offset + "   " + fun_lab_name + "\n" );
          }
            Map<String,Integer> m1 = classesmapinfo.get(classname).offset_map_var;
            for(Map.Entry<String,Integer> entry:m1.entrySet()){
               String var_name = entry.getKey(),var_offset = Integer.toString(entry.getValue());
               newallocator+=("HSTORE  TEMP  " + temp2 + "  " + var_offset + "   0\n" );
            }
          newallocator+=("HSTORE TEMP  " + temp2 + " 0  TEMP  " + temp1 + "\nRETURN   TEMP  " + temp2 + "\n\nEND\n");
         }
         if(in_msg_class_call){
            currtype = temp.toString();
         }
         // System.out.println("llllll\n" + newallocator + "\nllllll");
         _ret = (R)newallocator;
      return _ret;
   }

   /**
    * f0 -> "!"
    * f1 -> Expression()
    */
   public R visit(NotExpression n, A argu) {
      R _ret=null;
      n.f0.accept(this, argu);
      String expr1 = n.f1.accept(this, argu).toString();
       String labelString1 = Integer.toString(labelno);
      labelno++;
      String labelString2 = Integer.toString(labelno);
      labelno++;
      int present_temp_count = classesmapinfo.get(currclassname).class_funcinfo.get(currmthd_label).total_temp_count;
      classesmapinfo.get(currclassname).class_funcinfo.get(currmthd_label).total_temp_count++;
      String pres_temp_String = Integer.toString(present_temp_count);
      _ret = (R)("\nBEGIN\n\n" +
                  "CJUMP  NE " + expr1 + " 0  L" + labelString1 + "\n" +
                  "MOVE   TEMP   " + pres_temp_String + "   0\n" +
                  "JUMP  L" + labelString2 + "\n" +
                  "L" + labelString1 + "   MOVE TEMP " + pres_temp_String + "  1\n" +
                  "L" + labelString2 + "  NOOP RETURN TEMP " + pres_temp_String + "\n\nEND\n"  );
      return _ret;
   }

   /**
    * f0 -> "("
    * f1 -> Expression()
    * f2 -> ")"
    */
   public R visit(BracketExpression n, A argu) {
      R _ret=null;
      n.f0.accept(this, argu);
      R expr1 = n.f1.accept(this, argu);
      n.f2.accept(this, argu);
      _ret = (R)(expr1.toString());
      return _ret;
   }

}
